### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxelib#10]
For uploading new packages, it would be great to support https connections so the password isn't passed as clear text

**Comment by ibilon** [comment]
Instead of making it a two-step build it'd be easier to add hxssl as a git submodule and bringing it in the classpath.

**Comment by pqyptixa** [comment]
Please, also add support for downloading packages through HTTPS as well. Anyone can see and modify packages on the fly.

**Comment by RealyUniqueName** [comment]
haxelib client uses https by default now:
https://github.com/HaxeFoundation/haxelib/blob/c5afca81c7d8450007bafaf4248af1efaabf05c4/src/haxelib/client/Main.hx#L161-L163
