### ISSUE TITLE
Allow 'haxelib local' to take web url

### ISSUE THREAD

**Issue by hughsando** [HaxeFoundation/haxelib#105]
It would be nice to be able to point haxelib at a "wget" url as well as a local file.

**Comment by alebianco** [comment]
@back2dos 
just for confirmation, the syntax _haxelib install http://host/archive.zip_ would not work in the current implementation, correct? 
I think that would be enough to solve the issue

**Comment by nadako** [comment]
I think we can merge this issue into #238, since we're discussing npm-like url support there.
