### ISSUE TITLE
Local Repositories

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxelib#141]
The ability to have several haxelib repos on the same computer (and per-project setup) has been mentioned as part of the WWX discussions. Here we can discuss actual proposals on how this would work in practice before implementing it.

This might be as easy has allowing a ".haxelib" per project that would store the path to the used haxelib repo

**Comment by back2dos** [comment]
Ok, after talking with @ncannasse we're adding this. I have fixed the selfupdate issue and added a `--global switch` that allows to fall back to the global repo from a local one (might be useful for `haxelib run`).

I have also talked with @jasononeil and we intend to pursue a different strategy. More on that later though.
