### ISSUE TITLE
New Haxelib Website

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxelib#143]
I am creating this issue as a tracker for all the website related work.

#14 Design of the website

The design discussion so far includes:

* CSS to match main Haxe site
* Add a README.md
* Dart's "Pub" tool had a nice design: http://pub.dartlang.org/

#10 Https Support
#33 Cloudfare support (or some other cloud provider to improve download speeds)
#91 User management (password reset etc)
#69 Dox support

Other things I can think of:

* Download statistics so we know what is popular
* Display information about dependencies (maybe version by version)
* A homepage that explains what haxelib is (links to manual?) and how to use it, not just a list of libs.
* A homepage that shows both popular and recent libs, not just recent.

Any other things we would like to discuss add a comment here, or if there are other issues create a link here so we can track them.

**Comment by fzzr-** [comment]
Maybe yes. I like idea about tags. 
Also we need a really smart search and web-api.
