### ISSUE TITLE
Page not found HTTP status 200 instead of 404

### ISSUE THREAD

**Issue by bsideup** [HaxeFoundation/haxelib#153]
Hi!

If I will request non-existing file, for example http://lib.haxe.org/files/3.0/away3d-examples-1,0,3-alpha1.zip , lib.haxe.org will render page with HTTP status 200, but it should be 404. 

It's important to get 404 because otherwise it's hard to determine if library exists or not. 

Could you please make it 404?

Thanks!

**Comment by Simn** [comment]
We now have a proper page not found page for this.

**Comment by bsideup** [comment]
@Simn 

```
$ curl -v http://lib.haxe.org/files/3.0/away3d-examples-1,0,3-alpha1.zip
* Hostname was NOT found in DNS cache
*   Trying 5.39.76.185...
* Connected to lib.haxe.org (5.39.76.185) port 80 (#0)
> GET /files/3.0/away3d-examples-1,0,3-alpha1.zip HTTP/1.1
> User-Agent: curl/7.37.1
> Host: lib.haxe.org
> Accept: */*
>
< HTTP/1.1 200 OK
```


No you don't >_<

**Comment by explorigin** [comment]
Still getting this: http://lib.haxe.org/p/classmap/1.0.0/files/classmap/

**Comment by nadako** [comment]
Seems to be correct now:
```
F:\Code\haxe>curl -v http://lib.haxe.org/files/3.0/away3d-examples-1,0,3-alpha1.zip
...
< HTTP/1.1 404 Not Found
...
```
