### ISSUE TITLE
Setting dev to library subfolder

### ISSUE THREAD

**Issue by ProG4mr** [HaxeFoundation/haxelib#160]
It would be great if i could set the dev folder to a subfolder like the git command:

```
haxelib dev libname git
```

and it would set the dev lib to:
```
C:\HaxeToolkit\haxe\lib\libname\git
```

or other subfolder, with this i could switch bettween haxelib and git versions without much trouble.

Using windows 7 64 bits - Haxelib 3.1.0-rc.4

**Comment by ibilon** [comment]
(

**Comment by ibilon** [comment]
(a couple months after your issue was open, but since it's still open)

@ProG4mr you can do `haxelib set libname git`.

**Comment by ProG4mr** [comment]
Thanks @ibilon i think the ```set``` command is a good alternative to switch development versions of a library instead of using ```dev``` command, seems to be solved.
