### ISSUE TITLE
Parse "see changes.md" and print to description

### ISSUE THREAD

**Issue by as3boyan** [HaxeFoundation/haxelib#162]
You know, I and @fzzr- find such description not useful and hard to read. I think that it would be better this way.

For example

```markdown
1.1.1
+ADDED: some feature that only I exited about(but I think everybody should have that)

1.1.0
+FIX: fixed bug added in previous version
etc
```

And if `version` in `haxelib.json` matches `changes.md` paragraph/line/field, then it will be taken from there.

**Comment by fzzr-** [comment]
:+1: I think we need to implement "garbage searcher" as part of Haxelib's validator - no approve if garbage existing or changes.md/txt mentioned.

Garbage for example:
* .git/.hg dirs
* OS's internal hidden files
* Simlinks (!!!) yes, I seen it!
* changes-file in description where length less then five words
.

**Comment by as3boyan** [comment]
Good idea. If there is a changes.md/txt - then client should look for description there, if there is none - do not approve release with notice, that info for release should be added something like that.

**Comment by ncannasse** [comment]
While I agree with the "garbage" thing (I recently had to move haxelib storage to another partition because we lacked disk space), I don't think we should enforce people to describe changes in their lib, given that most people don't read them anyway.

**Comment by fzzr-** [comment]
One more argument in favor of mandatory cleaning of garbage (such as `.file`, `.dir`, sim-links, etc..).
https://github.com/openfl/lime/issues/373#issuecomment-84447703

**Comment by jasononeil** [comment]
I don't think we can expect people to keep their change log in a certain format.  Now that you can view "CHANGES.md" from the website it's not that much work for you to find it :)
