### ISSUE TITLE
Summary after upgrade

### ISSUE THREAD

**Issue by initialize** [HaxeFoundation/haxelib#163]
Minor feature request: 

Since haxelib upgrade generates quite massive output, way longer than my console backlog, it would be nice with a summary by the end.

I'm thinking something like:
```
> haxelib upgrade
(...)
Summary:
    somelib: 0.9.1 -> 0.9.47
    otherlib: 1.7.0 -> 2.0.1
Done
>

```

**Comment by ibilon** [comment]
Should we just do that (nothing preventing it) or only when in verbose mode,
and when not in verbose mode simply not print a line for __every__ file and directory installed?

**Comment by nadako** [comment]
I find current verbosity settings quite weird (`quiet` vs `debug`, they are only used for printing in the `Vcs` module, and initially `debug` was just an option to show exception stacktraces). I'd rather have a quiet (but not silent) default, verbose with lots of extra outputs, and a hidden debug mode which enables verbose and stacktraces.

But oh well, I think we could move those `Created`/`Installed` lines to the `debug` verbosity as that info isn't really useful for end-user.
