### ISSUE TITLE
haxelib submit broken using latest haxe

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxelib#164]
```shell
$ haxelib submit haxelib.zip
/usr/local/Cellar/haxe/HEAD/lib/haxe/extra/haxelib_src/src/tools/haxelib/Data.hx:239: characters 28-31 : Unknown identifier : doc
```

@back2dos would you take a look?

**Comment by Simn** [comment]
Are you saying this broke after updating Haxe?

**Comment by andyli** [comment]
I meant the error occurs when using the latest development branch of haxe, together with the latest master branch of haxelib.

`haxelib` is run using the script generated by `make install`:
```
#!/bin/sh
exec haxe -cp /usr/local/Cellar/haxe/HEAD/lib/haxe/extra/haxelib_src/src --run tools.haxelib.Main "$@"
```

**Comment by back2dos** [comment]
Uhm, will do.

**Comment by back2dos** [comment]
Is this still an issue?

**Comment by andyli** [comment]
Yes. It still behaves the same as I said in the previous comment.

**Comment by back2dos** [comment]
Any clue as to what haxelib_src might be?

**Comment by andyli** [comment]
"haxelib_src" is the source of haxelib, checked out the master branch with the latest commit 94e233284e1bae7a1324e6ce58b7084465c4f2a3.

In fact, the issue can be reproduced by:
```
haxe -cp path/to/haxelib_src --run tools.haxelib.Main submit packagedLib.zip
```

**Comment by ncannasse** [comment]
I'm starting to think it was a very bad idea to move haxelib outside of haxe GIT...

**Comment by back2dos** [comment]
Can you elaborate?

**Comment by ncannasse** [comment]
Well, it seems even harder than before to take decisions, nobody seems to feel responsible for fixing things (maybe I should ?), and regressions are introduced without (almost) anyone noticing or reacting.

**Comment by Simn** [comment]
I'll go on strike if you bring this back into my field of vision!

**Comment by ncannasse** [comment]
[edit] (maybe @Simn should ?)  :-)

**Comment by back2dos** [comment]
Yes, this project clearly lacks any kind of leadership. And it's hard to step into the role without the foundation laying out project goals. I would be willing to take on more responsibility, but I'd rather not have to go get feedback, particularly if it's not given or given after several months. Anyway, this is probably something to discuss at the WWX and not here.

**Comment by waneck** [comment]
This issue is probably related to the use of macros on haxelib. `haxe --run` is run on the macro context, so it cannot contain any macros ( like https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Validator.hx#L153 ). I think we need to solve this before 3.2-rc

**Comment by waneck** [comment]
By the way, I can reproduce this as well

**Comment by jonasmalacofilho** [comment]
The fix for this hasn't been included in the latest client in the server and available to 'selfupdate'.

**Comment by Simn** [comment]
It should be in the latest release.

**Comment by back2dos** [comment]
@jonasmalacofilho Done.
