### ISSUE TITLE
Ability to rename library by changing json and resubmitting

### ISSUE THREAD

**Issue by scriptorum** [HaxeFoundation/haxelib#165]
If you rename the library in your json file and re-submit it to Haxelib, the name should updated on http://lib.haxe.org. 

Similar to issue #151, after submitting  [Flaxen](http://lib.haxe.org/p/Flaxen) to the library, I realized lower-case is a more common naming convention. I now have the name as `flaxen` in the json, but after submitting it still shows as `Flaxen` in the lib. Functionally, it doesn't affect my install instructions because project names are case-insensitive, but it would be nice to be consistent. 

Meanwhile, my github repo is in uppercase as well, but that's not your problem... ;)

**Comment by jgranick** [comment]
I would like to see an ability to rename a haxelib, but this gets more complex when it is more than just changing the case. I'm not sure that only a haxelib.json change would work, since that does not let "submit" know what the previous name was

**Comment by jasononeil** [comment]
I think we go for a "rename" or "deprecate" ability through the web interface.  Let's handle this in #168
