### ISSUE TITLE
-y flag for Haxelib upgrade - yes to all upgrades

### ISSUE THREAD

**Issue by cambiata** [HaxeFoundation/haxelib#167]
To prevent severe Y finger repetitive strain injuries, it would be cool with an -y flag that would bypass all the "Upgrade library-x to 0.1.2 [y/n/a] ?" questions with "y" answer.

**Comment by ncannasse** [comment]
That's what "a" is for no ? (always)

**Comment by Simn** [comment]
The idea is to run it in non-interactive mode. Although I thought there was an option for that already...

**Comment by fserb** [comment]
Been using haxelib for more than a year. Just figured out what the "a" is for. :)

**Comment by jasononeil** [comment]
I'm pretty sure there are cases when selecting "a" doesn't work also.  When
I do a complex installation (many hxml files, each with many libs, most
with furhter dependencies) I find myself pressing "a" dozens of times.

I've never bothered to look into it but it would be nice to fix when we fix
this one also.
