### ISSUE TITLE
`haxelib git` should install submodules

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxelib#173]
When using the `haxelib git` command, it should also initialize and update submodules if they exist

**Comment by Simn** [comment]
I feel like haxelib git was a bad idea and we shouldn't spend any more time on it. But it's not up to me.

**Comment by jgranick** [comment]
Yeah, I encourage people to avoid it, personally I use `haxelib dev` with my own checkout, but I have some users who have this problem

**Comment by nadako** [comment]
Why? It works for me so far.

**Comment by ncannasse** [comment]
I like haxelib git too, maybe simply adding --recursive would be enough ?

**Comment by Simn** [comment]
And then the next person wants something else which is normally available through the git command line. Where does it end?

**Comment by nadako** [comment]
Well, submodules are quite particular feature that is used very often.

**Comment by jgranick** [comment]
I can't think of a reason to not do it recursively by default

One of my issues with `haxelib git` is that it does not understand if `git` is not available as a command in your PATH. As a result, a `haxelib git` directory (done in a Windows GIT bash) will cause trouble any time you `haxelib install` or `haxelib upgrade` from a regular Windows command-prompt

This isn't an issue on a Linux or Mac machine, generally

**Comment by back2dos** [comment]
Fair enough. It could thus be `--flat` for non-recursive cloning.

Also, can you please open another ticket for the other issue you have described?

**Comment by back2dos** [comment]
I haven't got the chance to test this. Does anybody have an example repo I could test this against? @jgranick maybe?
