### ISSUE TITLE
It would be nice if `haxelib git` failed silently during `haxelib upgrade`

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxelib#175]
Moving over from #173 :smile:

It would be great if `haxelib git` did not error when `git` is not available, instead, I think it would be nice if this command printed a warning that it was not able to update since `git` was not available, then it could continue. This is ideal for environments where GIT is not always in your path (such as a Windows GIT bash versus a traditional command prompt)

Thanks!

**Comment by back2dos** [comment]
Oh, thanks for clarifying.

**Comment by Simn** [comment]
I don't get it, why would haxelib GIT not fail if you don't have git installed?

I don't like silent failures very much, especially not as default behavior.

**Comment by back2dos** [comment]
@Simn: The scenario is that you install a library with `haxelib git` from an environment where `git` is available, and then run `haxelib upgrade` from an environment where it isn't, which then will choke as soon as it tries to update that thing.

**Comment by Simn** [comment]
This issue title has haxelib git, not haxelib upgrade. It makes more sense for the latter.
