### ISSUE TITLE
Write tests for selfupdate

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxelib#181]
Given that the critical part of selfupdate can now be triggered with `haxelib local haxelib_client.zip --always`, setting up testing for it should be fairly straight forward.

**Comment by nadako** [comment]
After the merge of #291, `selfupdate` is now a mere (deprecated) alias for `haxelib update haxelib`, so we should rather add tests for the whole "run installed haxelib from bundled one" instead. I'll look into writing some.

I'll close this issue as I don't really see the its point anymore. We need more tests in many areas but we don't create issues about that. :)
