### ISSUE TITLE
Allow for library versions to define compatible Haxe versions

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxelib#182]
The client should then filter based on the current version, particularly in `Data.getLatest`.

**Comment by back2dos** [comment]
I consider this selfupdate related, because in the future we don't want old setups to selfupdate haxelib to versions that are incompatible with the locally available Haxe version.

**Comment by ncannasse** [comment]
The problem is the following : I don't think we can automate this, and I don't think we can rely on the users to correctly tag their libraries :)

**Comment by back2dos** [comment]
This is strictly intended as an opt-in. Nobody *has* to use this feature. By default haxelib will assume all language versions are compatible. And I do think in the future some library maintainers will be happy to be able to drop support for older language versions without messing up old setups. And even if nobody else uses this except haxelib_client, I think we can make good use of it ;)

**Comment by nadako** [comment]
Let's merge this into #234
