### ISSUE TITLE
haxelib consumes the debug flag?

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxelib#184]
This is a regression in 3.2.0-rc.1 release:

```
> CLI
haxelib run flow run --debug --wtf

> Inside haxelib run (see below)
Flow.hx:19: [run,--wtf,/Users/sven/dev/test/]

```

What happened to --debug!!? 
I can't tell if this is from haxelib specifically but I dont think it's in `Sys.args();`

```
//Flow.hx

    static function main() {

        var sys_args = Sys.args();

        trace(sys_args);
```

**Comment by jasononeil** [comment]
@back2dos, would it be reasonable to consume flags before "run", and any
flags encountered after that are passed to the run command?

**Comment by T1mL3arn** [comment]
Recently I posted something like this here https://github.com/HaxeFoundation/haxe/issues/4021 , and here is more related issue. Now (with 3.2.0 rc1) the FlashDevelop not starting debug session and moreover, flash app is compiled each time as release version even if I use debug option from FD or from console.

**Comment by back2dos** [comment]
That's already fixed, just not deployed:
https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Main.hx#L329

**Comment by underscorediscovery** [comment]
Any idea when that might be in the packaged build? (@simn has been updating the rc.1 packages with fixes in the mean time). 

It is pretty difficult to test 3.2.0 for bugs without a debug flag in all my haxelib run workflows :)

**Comment by Simn** [comment]
I'll re-release again over the course of the day and let you know.

**Comment by back2dos** [comment]
@underscorediscovery You can try haxelib selfupdate for now.

**Comment by underscorediscovery** [comment]
It seems to be resolved (barring haxelib selfupdate breaking itself, but after resetting I think the debug flag is back thanks)
