### ISSUE TITLE
Using haxelib as a haxelib

### ISSUE THREAD

**Issue by hughsando** [HaxeFoundation/haxelib#186]
Creating an extra process and parsing data seems like overkill when we have a haxelib sitting there in a haxelib and it makes me sad.
I suggest the following:
Move 99% of the code out of "Main" and put in in Haxelib, with main, just:
```
  var haxelib = new Haxelib(Sys.args());
  haxelib.process( );
 
 And Haxelib.hx

 public function new( args )
 public function getRepository( ?setup : Bool ) 
 public function function checkRec( ...)
```
Even making new and checkRec and args public would make this work as a library.

**Comment by back2dos** [comment]
This is planned for obvious reasons. 

I've discussed it with @jasononeil and we really want to decouple the CLI and the underlying client logic. It's not really reasonable to have to pass in your arguments as an array, or have it just access your stdin if there's not enough of them.

If you are happy with the current interface, you can just use `@:privateAccess` for the time being ;)

**Comment by hughsando** [comment]
Yes, this is fair enough.
I guess that as a library, a "read only" api might be simple.  The only one I would really use is "where is this library[:version]".  A List/Array of {name,version,isCurrent,directory,dependency[]} would be icing on the cake. Not too far off checkRec.

**Comment by nadako** [comment]
Let's merge this with #186

**Comment by ibilon** [comment]
@nadako wrong link ;)

**Comment by nadako** [comment]
Oops, I probably meant #217 :)
