### ISSUE TITLE
Installing lime fails

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxelib#187]
Using haxe-3.2.0-rc.2 linux 64 bits and its bundled haxelib installing lime fails.

```
$ haxelib install lime
Downloading lime-2,1,3.zip...
Download complete : 87961405 bytes in 18.9s (4539.1KB/s)
  Created project/
  Created project/common/
  Install project/common/Extension.cpp
  Install project/common/ExternalInterface.cpp
  Created project/include/
  Install project/include/Utils.h
  Install project/Build.xml
  Install Extension.hx
  Install haxelib.json
  Created dependencies/
  Created dependencies/android/
  Install dependencies/android/project.properties
  Install dependencies/android/build.xml
  Created dependencies/android/src/
  Created dependencies/android/src/org/
  Created dependencies/android/src/org/haxe/
  Created dependencies/android/src/org/haxe/extension/
  Install dependencies/android/src/org/haxe/extension/Extension.java
  Install dependencies/android/AndroidManifest.xml
  Install include.xml
  Current version is now 1.0.0
Done
```

and ends up like this:
```
$ haxelib list
unknown: [1.0.0]
```

Downloading the zip from the website and using haxelib local fails too,
the zip is correct and manually extracting it works.

I installed actuate, box2d, HaxePunk, hxcpp, layout, openfl-samples, openfl and swf without any problems.

**Comment by adamscott** [comment]
Same here! On Mac OS 10.10 (Yosemite) x64.

**Comment by delahee** [comment]
I had the same issue because my lime directory was locked by my anti virus,
no error spawned...

**Comment by jgranick** [comment]
This just happened to me as well. Is it because Lime includes a ".gitignore" file? Does it stop extracting when it hits a "." file, rather than skipping and continuing?

**Comment by jgranick** [comment]
Nevermind, this was fixed after I ran `haxelib selfupdate`

I wish haxelib were able to update during a "haxelib upgrade" like other libraries ;)

**Comment by ibilon** [comment]
I ran a selfupdate but it didn't fixed it.

haxelib:
```
#!/bin/sh
OLDCWD=`pwd`
cd /usr/lib/haxe/lib/haxelib_client/3,2,0-rc,2/src/
exec haxe -D haxelib_client=3.2.0-rc.2 --run tools.haxelib.Main -cwd $OLDCWD
```
but
`Haxe Library Manager 3.2.0-rc.1 - (c)2006-2015 Haxe Foundation`

Was the string not updated or did my selfupdate didn't succeed?

**Comment by jgranick** [comment]
Actually, `haxelib install lime` failed like above, downloading manually from http://www.openfl.org/builds/lime and running `haxelib local <name of zip>` also failed. I ran `haxelib selfupdate`, then I used `haxelib local` again. I didn't actually test `haxelib install` again after the update

**Comment by Simn** [comment]
We should check this before release.

**Comment by ibilon** [comment]
Following @jgranick's idea I tried removing all files starting with a "." from the lime zip and then doing a `haxelib local`, it fixes the error.

**Comment by back2dos** [comment]
Fixed here (sorry, flipped the issue number): https://github.com/HaxeFoundation/haxelib/commit/68f25d97dc991516c02a2665081ba5cc0d2ae23e

**Comment by Simn** [comment]
Remind me to sync haxelib as soon as I start behaving like I'm about to package a Haxe release.

**Comment by back2dos** [comment]
Will do.

**Comment by c0ffeeartc** [comment]
same as first post, but for version 2,3,3

**Comment by c0ffeeartc** [comment]
Solved it.
Problem was `haxelib selfupdate` couldn't update as in https://github.com/HaxeFoundation/haxelib/issues/189

    $chmod 777 /usr/bin/haxelib
    $cp /usr/bin/haxelib ~/
    $cd ~
    $./haxelib selfupdate

and lime installed fine.
