### ISSUE TITLE
Cannot submit Lime to haxelib (3.2.0-rc.1)

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxelib#192]
I cannot submit Lime to haxelib using haxelib 3.2.0-rc.1, it says:

    `"::extension::"` contains invalid characters

This is coming from the "templates/extension/haxelib.json" file. I can't figure out how to update haxelib on Linux (since "selfupdate" fails) so I'm sorry I can't say if this is fixed or not

**Comment by back2dos** [comment]
This is the same issue as #187.

**Comment by jasononeil** [comment]
@back2dos is this fixed then?

**Comment by jgranick** [comment]
No, this is different. This is running `haxelib submit lime.zip`, it's recursively looking inside the zip and finding another haxelib.json deeper in the file structure. I think it should find the first haxelib.json at the top and exit, perhaps?

**Comment by andyli** [comment]
Then it should be the same as #122, which should be fixed. Can you check?

**Comment by back2dos** [comment]
It's the same issue. I had left a mistake in the code that finds the topmost JSON (path-wise), which causes errors both for uploading and installing. This should be working with 3.2.0-rc.3. Can you please confirm and close @jgranick ?

**Comment by Simn** [comment]
No feedback - assume fixed.
