### ISSUE TITLE
haxelib git

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [HaxeFoundation/haxelib#194]
when doing a

```
haxelib upgrade
```

and it comes across a library, that is installed via git, it tells me:

```
Could not execute git, please make sure it is installed and available in your PATH.
```

But git is in /usr/bin and /usr/bin is in my path.

I am on ubuntu 14.10 64 bit.

**Comment by fzzr-** [comment]
@RudolfVonKrugstein What is version you using? Please execute `$ haxelib version`.

**Comment by RudolfVonKrugstein** [comment]
I did a complete reinstall in the mean time. It all works now. I do not know anymore which version I had installed at that time :-(.
