### ISSUE TITLE
Can't submit library

### ISSUE THREAD

**Issue by adireddy** [HaxeFoundation/haxelib#198]
I am seeing this today when trying to submit a new library.

File #73093867 accepted : 302383 bytes written
Processing file.... 
Invalid response : 'Error : Cannot serialize [file_open,out.txt]
Called from C:\HaxeToolkit\haxe\std/haxe/Serializer.hx line 515
Called from C:\HaxeToolkit\haxe\std/haxe/Serializer.hx line 534
Called from C:\HaxeToolkit\haxe\std/haxe/remoting/HttpConnection.hx line 105
Called from C:\HaxeToolkit\haxe\std/haxe/remoting/HttpConnection.hx line 81
Called from tools/haxelib/Repo.hx line 41
Called from tools/haxelib/Repo.hx line 317
Called from tools/haxelib/Repo.hx line 323
Called from ? line 1
Called from /usr/lib/haxe/std/neko/vm/Module.hx line 52
Called from Tora.hx line 340
Called from /usr/lib/haxe/std/neko/vm/Loader.hx line 154
Called from /usr/lib/haxe/std/neko/vm/Loader.hx line 132
Called from Tora.hx line 486'

**Comment by back2dos** [comment]
Can you try again, please? It seems I had left some debug code in the build.

**Comment by adireddy** [comment]
Works now :+1:
Thanks.

**Comment by eliasku** [comment]
Now for 3.3.0-rc1
Reopen?

```
Sending data.... 
File #37709025 accepted : 25900 bytes written
Processing file.... 
Error: Invalid response : 'Error : Cannot serialize [file_open,/var/www/html/files/3.0/hotmem-0,0,2.zip]
Called from /usr/share/haxe/std/haxe/Serializer.hx line 522
Called from /usr/share/haxe/std/haxe/Serializer.hx line 541
Called from /usr/share/haxe/std/haxe/remoting/HttpConnection.hx line 108
Called from /usr/share/haxe/std/haxe/remoting/HttpConnection.hx line 84
Called from haxelib/server/Repo.hx line 43
Called from haxelib/server/Repo.hx line 355
Called from haxelib/server/Repo.hx line 361
Called from ? line 1
Called from D:\Projects\haxe/std/neko/vm/Module.hx line 52
Called from Tora.hx line 333
Called from D:\Projects\haxe/std/neko/vm/Loader.hx line 154
Called from D:\Projects\haxe/std/neko/vm/Loader.hx line 132
Called from Tora.hx line 479'
```

**Comment by eliasku** [comment]
![image](https://cloud.githubusercontent.com/assets/3038174/18220259/d52d3ef6-7178-11e6-834a-fce490444616.png)

**Comment by chiguire** [comment]
This is still happening for Haxe 3.2.1, is there something I'm missing?

'''
File #19866523 accepted : 38992 bytes written
Processing file....
Invalid response : 'Error : Cannot serialize [file_open,/var/www/html/files/3.0/traceryhx-1,0,1.zip]
Called from /usr/share/haxe/std/haxe/Serializer.hx line 522
Called from /usr/share/haxe/std/haxe/Serializer.hx line 541
Called from /usr/share/haxe/std/haxe/remoting/HttpConnection.hx line 108
Called from /usr/share/haxe/std/haxe/remoting/HttpConnection.hx line 84
Called from haxelib/server/Repo.hx line 43
Called from haxelib/server/Repo.hx line 355
Called from haxelib/server/Repo.hx line 361
Called from ? line 1
Called from D:\Projects\haxe/std/neko/vm/Module.hx line 52
Called from Tora.hx line 333
Called from D:\Projects\haxe/std/neko/vm/Loader.hx line 154
Called from D:\Projects\haxe/std/neko/vm/Loader.hx line 132
Called from Tora.hx line 479'
'''

**Comment by chiguire** [comment]
I'm getting a similar error like this, I'm using Haxe 3.2.1. I managed to submit the package the first time correctly, but now it won't allow me to update the package.

```
Sending data....
File #19866523 accepted : 38992 bytes written
Processing file....
Invalid response : 'Error : Cannot serialize [file_open,/var/www/html/files/3.0/traceryhx-1,0,1.zip]
Called from /usr/share/haxe/std/haxe/Serializer.hx line 522
Called from /usr/share/haxe/std/haxe/Serializer.hx line 541
Called from /usr/share/haxe/std/haxe/remoting/HttpConnection.hx line 108
Called from /usr/share/haxe/std/haxe/remoting/HttpConnection.hx line 84
Called from haxelib/server/Repo.hx line 43
Called from haxelib/server/Repo.hx line 355
Called from haxelib/server/Repo.hx line 361
Called from ? line 1
Called from D:\Projects\haxe/std/neko/vm/Module.hx line 52
Called from Tora.hx line 333
Called from D:\Projects\haxe/std/neko/vm/Loader.hx line 154
Called from D:\Projects\haxe/std/neko/vm/Loader.hx line 132
Called from Tora.hx line 479'
```

**Comment by andyli** [comment]
@eliasku @chiguire 
Thanks for reporting. Would you upload the zip files to dropbox and paste the link here? We need to reproduce the issue in order to fix it.

**Comment by eliasku** [comment]
@andyli 
[hxease.zip](https://github.com/HaxeFoundation/haxelib/files/453284/hxease.zip)
[hotmem.zip](https://github.com/HaxeFoundation/haxelib/files/453285/hotmem.zip)

**Comment by chiguire** [comment]
Thank you, Andy, here's the link
https://www.dropbox.com/s/mpu22temlfhnk8a/traceryhx.zip?dl=0

2016-09-03 9:24 GMT+01:00 Andy Li <notifications@github.com>:

**Comment by asciiascetic** [comment]
ditto:

```
haxelib submit farcek.zip 
Password : 
Sending data.... 
File #99411991 accepted : 5463 bytes written
Processing file.... 
Invalid response : 'Error : Cannot serialize [file_open,/var/www/html/files/3.0/farcek-1,5,0.zip]
Called from /usr/share/haxe/std/haxe/Serializer.hx line 522
Called from /usr/share/haxe/std/haxe/Serializer.hx line 541
Called from /usr/share/haxe/std/haxe/remoting/HttpConnection.hx line 108
Called from /usr/share/haxe/std/haxe/remoting/HttpConnection.hx line 84
Called from haxelib/server/Repo.hx line 43
Called from haxelib/server/Repo.hx line 359
Called from haxelib/server/Repo.hx line 365
Called from ? line 1
Called from D:\Projects\haxe/std/neko/vm/Module.hx line 52
Called from Tora.hx line 333
Called from D:\Projects\haxe/std/neko/vm/Loader.hx line 154
Called from D:\Projects\haxe/std/neko/vm/Loader.hx line 132
Called from Tora.hx line 479'
```

https://www.dropbox.com/s/plz7tk28z3h8yjp/farcek.zip?dl=0

**Comment by ncannasse** [comment]
It seems that it's not looking into the good directory, which should be (path/to/haxelib/files/....) - and I think it's not in /var/www/ is it?

**Comment by restorer** [comment]
Same story:

```
Sending data.... 
File #97840920 accepted : 128671 bytes written
Processing file.... 
Error: Invalid response : 'Error : Cannot serialize [file_open,/var/www/html/files/3.0/hxbolts-1,0,2.zip]
Called from /usr/share/haxe/std/haxe/Serializer.hx line 522
Called from /usr/share/haxe/std/haxe/Serializer.hx line 541
Called from /usr/share/haxe/std/haxe/remoting/HttpConnection.hx line 108
Called from /usr/share/haxe/std/haxe/remoting/HttpConnection.hx line 84
Called from haxelib/server/Repo.hx line 43
Called from haxelib/server/Repo.hx line 359
Called from haxelib/server/Repo.hx line 365
Called from ? line 1
Called from D:\Projects\haxe/std/neko/vm/Module.hx line 52
Called from Tora.hx line 333
Called from D:\Projects\haxe/std/neko/vm/Loader.hx line 154
Called from D:\Projects\haxe/std/neko/vm/Loader.hx line 132
Called from Tora.hx line 479'
```

http://temp.zame-dev.org/pub/hxbolts.zip

**Comment by andyli** [comment]
I can reproduce it by trying to update an existed version of jQueryExtern. Investigating now.

@ncannasse The path is correct. It is a symlink to the haxelib folder inside the container.

**Comment by andyli** [comment]
Should be fixed now. Please check!

**Comment by eliasku** [comment]
works!

**Comment by asciiascetic** [comment]
Ah just super. Thanks!
