### ISSUE TITLE
Error chdir crashes

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxelib#207]
```
/usr/lib/haxe/std/neko/_std/Sys.hx:87: characters 2-24 : Error chdir /Applications/Sublime
tools/haxelib/Main.hx:309: characters 17-43 : Called from
tools/haxelib/Main.hx:1508: characters 2-22 : Called from
--macro:1: character 0 : Called from
Aborted
```

Trying to use haxelib on 3.2.0-rc.3 version, is irregularly broken. 
It looks related to paths with spaces in them, as the only time I have this issue is when that is the case.

#191 could be related, I have used `haxelib setup` to a custom location.
#197 mentions this, but somehow ends with a PR for HG support, I have no idea how those relate.

This is becoming rather problematic in practice, as it affects all IDE's being able to query haxelib reliably, returning invalid results and sometimes errors in "unrelated" code, because the assumption is that haxelib isn't returning errors on stdout.

I'm filing the issue so that I can also look into it, hopefully when I have some time, but since there is so much going on behind the scenes with haxelib right now that isn't user facing, I have to assume it might already be fixed, somewhere.

Advice welcome!

**Comment by underscorediscovery** [comment]
Definitely related to spaces:

```
$ mkdir test
$ cd test
$ haxelib run something
//works
$ cd ../
$ mkdir "test test"
$ cd test\ test/
$ haxelib run something
//unrelated errors
```

Here's a paste from the above:
```
sven$ pwd
/Users/sven/dev/test test
sven$ haxelib run flow
Unknown command test
Haxe Library Manager 3.2.0-rc.3 
```

**Comment by underscorediscovery** [comment]
Also crashes : missing dev paths.

`haxelib dev libname ~/some_path/`
`rm -rf ~/some_path/`
`haxelib run libname`
`Error chdir ~/some_path/`

**Comment by back2dos** [comment]
Can you please open a separate issue for the latter and also make
suggestions as to what the behavior should be in that case?

**Comment by underscorediscovery** [comment]
I'm still trying to figure out exact problems without spamming the list, but sure I can move it to another issue.

**Comment by chichilatte** [comment]
Yep, i had this problem. I removed the space in a folder name and that fixed it. Thanks @underscorediscovery! (this was on OSX 10.7, haxelib 3.2.0-rc.3)

**Comment by KeyMaster-** [comment]
Just also bumped into this problem. My way of fixing it was to put double quotes around the working directory that is passed to haxelib in the `haxelib` executable script, like so:
`exec haxe -D haxelib_client=3.2.0-rc.3 --run tools.haxelib.Main -cwd "$OLDCWD" $@` (instead of simply `-cwd $OLDCWD`)

**Comment by nadako** [comment]
As I understand, this too is now "fixed" by the fact haxelib is not a shell script anymore, but a nekoboot-ed executable (#291)
