### ISSUE TITLE
private repositories

### ISSUE THREAD

**Issue by csomakk** [HaxeFoundation/haxelib#210]
Hi! We'd like to work with versioned private haxelibs. Any idea how to start on that?
Cheers

**Comment by ibilon** [comment]
You need to build the haxelib server, then you need to run it on your private server (something like apache + mod_tora) and change the server used by haxelib with the -R option.

**Comment by csomakk** [comment]
okay, that seemed complicated.. :) In the end we've made it to use our private git repo, and usage as follow:
dev dependency:
    $ haxelib dev [libname] [local folder]/src
release dependency:
    $ haxelib git [libname] [private git url] [branch/tag] src
