### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by Marc010** [HaxeFoundation/haxelib#219]
It's possible to upload the same version of a library multiple times. Haxelib should only display the most recent upload of a specific library version because that's the only version that can be installed anyways. Also the download counter seems to be always 0.

![haxelib duplicates](https://cloud.githubusercontent.com/assets/5739192/8081527/dc17d016-0f75-11e5-947a-f18b426ed430.PNG)

**Comment by nadako** [comment]
I see duplicate openfl versions on lib.haxe.org, but I can't reproduce that locally. Was it fixed by any chance?

**Comment by Simn** [comment]
I recently "force-pushed" hxparse twice and it only shows one version: http://lib.haxe.org/p/hxparse/versions/

Looks like this has been addressed indeed.
