### ISSUE TITLE
libraries with a dot in the name cannot be downloaded

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxelib#221]
Also the README.md doesn't show up for them probably because of the same issue.

**Comment by ibilon** [comment]
Note: this is a website issue, work normally in the cli tool.

For example perf.js:
http://lib.haxe.org/p/perf.js/1.0.2/files/ => `Invalid zip file /data/haxelib/www/../www/files/3.0/perf.js-1,0,2.zip: [file_open,/data/haxelib/www/../www/files/3.0/perf.js-1,0,2.zip]`
was saved as http://lib.haxe.org/files/3.0/perf,js-1,0,2.zip (note the dot converted to a comma)

**Comment by nadako** [comment]
Probably a missing `Data.(un)safe` somewhere

**Comment by fponticelli** [comment]
Thanks for the fix but I don't think it addresses the second part of it: "Also the README.md doesn't show up for them probably because of the same issue.". Should I open a new issue?

**Comment by ibilon** [comment]
I think it does, the readme is parsed by https://github.com/HaxeFoundation/haxelib/blob/master/src/website/controller/ProjectController.hx#L46-L53
`readContentFromZip` calls `readBytesFromZip` which calls `getZipEntries` which finally calls the fixed `getZipFilePath`

The ufront cache do need to be cleared though.

**Comment by fponticelli** [comment]
ok, cool ... thanks!
