### ISSUE TITLE
Unclear submit message

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxelib#223]
I'm trying to submit my first haxelib.  This is all I get.  I don't see any documentation that helps me understand what to do now.

```
timothy@sardis:~/projects/modular-js$ haxelib submit
Package : modular-js
std@sys_file_type
```

**Comment by ibilon** [comment]
You need to pass to submit a zip file containing your library.

**Comment by back2dos** [comment]
You can also use a directory, so in your case `haxelib submit .` would do.

**Comment by explorigin** [comment]
From http://lib.haxe.org/documentation/creating-a-haxelib-package/
"Alternatively you can run haxelib submit without a zip file to have haxelib zip and submit the current directory."

So this could be a bug to fix the website or add a better usage message.

**Comment by explorigin** [comment]
```haxelib submit .``` did work correctly though.  Thanks.

**Comment by Simn** [comment]
Speaking of unclear submit errors:

```
C:\GitHub\hxparse>haxelib submit hxparse.zip
Password :
Sending data....
File #6437501 accepted : 18254 bytes written
Processing file....
Invalid field access : iterator
```

**Comment by ncannasse** [comment]
@Simn any idea what's causing this ? I get the same error when trying to submit an update to hscript.

**Comment by Simn** [comment]
Sadly, no. I tried commenting out some of the Pokemon clauses but couldn't get any more information.

**Comment by ncannasse** [comment]
I think it comes from the server API since it's the "Processing file..." part

**Comment by explorigin** [comment]
Here's another fun one:

```
$ haxe build.hxml 
Error: Library msignal version 3.5.5 is not installed
```

build.hxml is
```
-cp app/src
-lib blork
-js dist/app.js
-main dapp.App
```

dapp is a fresh project that does not directly depend on msignal.

blork is a library project that is only installed locally and it depends on msignal.  It builds properly with no errors (with msignal).

Where is haxelib getting 3.5.5 from?

**Comment by Simn** [comment]
How is that related to haxelib submit?

**Comment by explorigin** [comment]
oops, you're right, I'll make a separate issue.

**Comment by underscorediscovery** [comment]
maybe @back2dos or @ibilon have ideas?

**Comment by ibilon** [comment]
Found the error, it's this line: https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Repo.hx#L148
The problem is that `info.tags` is null, adding `infos.tags = [];` just before allows the file to be submitted (tested with hxparse).

**Comment by ncannasse** [comment]
Data.readInfos should not return null when there are no tags @back2dos could you fix and make a new release ?

**Comment by back2dos** [comment]
@ncannasse In the future, could you please assign issues to me? It helps me keep track. Thanks.
