### ISSUE TITLE
[site, usability] remove ` target="_blank" ` from links

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxelib#224]
Need to remove `target="_blank"` attribute from all links on lib.haxe.org.
That site for developers. Please do not impose on opening links in a new window.

E.g.: in http://lib.haxe.org/p/gm2d link to Github ("Website") have `target="_blank"`.

**Comment by fzzr-** [comment]
We are not stupid and can decide how we want to open the link.

**Comment by Simn** [comment]
I agree this is a bit 1998.

**Comment by anissen** [comment]
:+1:

This issue continues to annoy me. I like being able to determine whether _I_ want to open a given link in a new tab or not.

**Comment by fzzr-** [comment]
plz! :warning:

**Comment by ncannasse** [comment]
FYI haxelib does not have a maintainer atm, @andyli will start working on various issues as soon as he's done with handling haxe packages for Linux.

**Comment by fzzr-** [comment]
Okay, excuse me.

**Comment by fzzr-** [comment]
Okay, excuse me. Can I help? I have a free one day per week.

**Comment by jasononeil** [comment]
I've fixed this issue.  I've always preferred links to external sites to open in new tabs but I guess I am in the minority on this one.

@fzzr- I'll send you an email - I'm sure help would be appreciated but the Haxelib project is pretty overwhelming.

**Comment by fzzr-** [comment]
@jasononeil :+1: Thank you. I wrote email to you.

**Comment by anissen** [comment]
This issue seem to have re-appeared :(

**Comment by fzzr-** [comment]
Thanks!
