### ISSUE TITLE
[site, readme] html-comments in markdown 

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxelib#226]
For example [here (http://lib.haxe.org/p/redhawk)](http://lib.haxe.org/p/redhawk) comments aren't ignored and we see `<!-- START doctoc generated TOC please keep comment here to allow auto update -->`.
Need to fix md-parser.

**Comment by Simn** [comment]
@jasononeil @dpeek: Is that a haxe-markdown problem?

**Comment by fzzr-** [comment]
Also sublists like this:

- foo
  - sub foo
    - sub sub foo
    - sub sub bar

**Comment by fzzr-** [comment]
related issue: https://github.com/HaxeFoundation/haxelib/issues/162

**Comment by jasononeil** [comment]
I can confirm this is a markdown problem.

I've created an issue over there: https://github.com/dpeek/haxe-markdown/issues/23

Should be a one line pull request fix if anyone wants to give it a go!
