### ISSUE TITLE
Please remove hxtelemetry verson 0.0.1

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxelib#227]
This was a placeholder version I published before publishing the beta (0.2.0-beta), but unfortunately it's now blocking download of the beta (being non-beta).

I could upload a new (non-beta) version, but I'd prefer to keep 0.2.0 marked as beta.

Thanks!

**Comment by ibilon** [comment]
Several `0.3` versions non-beta was pushed,
so I guess this isn't relevant anymore? @jcward

**Comment by jcward** [comment]
Correct, closing.
