### ISSUE TITLE
SVG logo problem on IE

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/haxelib#229]
SVG logo is mis-scaled, because IE: it's not the size to the img tag but the original, larger, SVG size.
https://css-tricks.com/scale-svg/

**Comment by nadako** [comment]
@markknol This is the same problem as https://github.com/HaxeFoundation/haxe.org/pull/93, right? I wonder if we could re-use those icons from haxe.org instead of duplicating them on lib.haxe.org...

**Comment by ibilon** [comment]
I think implementing https://github.com/HaxeFoundation/haxe.org/issues/61#issuecomment-76065910 would be a good idea to do that.

**Comment by nadako** [comment]
Agreed!

**Comment by markknol** [comment]
I dont know if lib.haxe uses a different logo but i will change its navigation soon too so I can update that too if it does not happen before that time.
