### ISSUE TITLE
Allow object constraints on @:generic to work with abstracts

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxelib#230]
It would be nice for [this](http://try.haxe.org/#62001) to work:

```
class Test {
    static function main() {
        foo(new Foo('foo'));
    }
    @:generic static function foo<T:{ var length(get, never): Int; }>(v:T) {
        
    }
}

abstract Foo(String) {
    public var length(get, never):Int;
    inline function get_length() return this.length;
    public function new(s) this = s;
}
```

Currently it doesn't, because abstracts and objects don't unify. But since the function is generic and `T` is known at compile time, could we not make an exception?

**Comment by ibilon** [comment]
Wrong repository?

**Comment by back2dos** [comment]
Why am I standing in the bathroom with a frying pan in my hand? :D

**Comment by nadako** [comment]
Haha, that comment made my morning :-)
