### ISSUE TITLE
"haxelib run" and special chars in arguments

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxelib#233]
This example run "run.n" which just print specified command-line arguments on separate lines:
```
C:\CmdBug>haxelib run CmdBug "abc"""def" 123
abc"def 123 C:\CmdBug/

C:\CmdBug>neko run.n "abc"""def" 123
abc"def
123
```
As you can see `haxelib run` and `neko run.n` works differently: `neko run.n` produce correct output (two arguments), while `haxelib run` do it wrong (concat all arguments into single long argument).

Test to run: http://haqteam.com/CmdBug.zip
(Just run "make.cmd" to see the bug.)

**Comment by andyli** [comment]
Probably because of #3603 and #3402

**Comment by ibilon** [comment]
Both of these issues were closed, and it looks from what I read like the escaping issue is gone;
can you confirm @andyli?

**Comment by andyli** [comment]
Right, it should no longer happen with the next release of haxe and neko.
