### ISSUE TITLE
-notimeout has no effect after message : "Sending data..."

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/haxelib#235]
without -notimeout:
```
haxelib submit lib.zip
Http connection timeout. Try running haxelib -notimeout <command> to disable timeout
```

with -notimeour
```
haxelib -notimeout submit lib.zip
Password :
Sending data....
Http connection timeout. Try running haxelib -notimeout <command> to disable timeout
```

**Comment by ibilon** [comment]
The timeout parameter is ignored for the next step (processing) https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Main.hx#L654 but normally not for this one.

Maybe the error message is too broad https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Main.hx#L482 and the error is not timeout related? (just guessing here)

**Comment by juef17** [comment]
This seems to be an issue with `install` as well:

```
C:\Users\juef>haxelib install openfl
Downloading openfl-3,5,3.zip...
Download complete : 0 bytes in 10.5s (0KB/s)
Http connection timeout. Try running haxelib -notimeout <command> to disable timeout

C:\Users\juef>haxelib -notimeout install openfl
Downloading openfl-3,5,3.zip...
Download complete : 0 bytes in 10.5s (0KB/s)
Http connection timeout. Try running haxelib -notimeout <command> to disable timeout
```

**Comment by nadako** [comment]
Looks like `-notimeout` only has effect on remoting calls, not on general http request, for which it should be done using `Http.cnxTimeout` field.

**Comment by nadako** [comment]
This should work now.
