### ISSUE TITLE
Haxelib versions listed on site are out of order

### ISSUE THREAD

**Issue by tbrosman** [HaxeFoundation/haxelib#236]
This is (sortof) related to https://github.com/HaxeFoundation/haxelib/issues/83. The versions listed on the site are in lexical order and not version/date order. This causes some interesting user behavior (although I guess it's possible version 0.8.0 worked better for some people than versions 0.10.0+, in which case please open a bug!):

![all versions of hxmath](https://cloud.githubusercontent.com/assets/3754050/9243531/9a515e7e-4146-11e5-943c-9f9b970760a9.png)

**Comment by nadako** [comment]
I'll reopen this since the bug is still there until we deploy a new website version.

**Comment by nadako** [comment]
@back2dos @jasononeil what is the process of updating haxelib website? it would be nice to have this fix deployed!

**Comment by nadako** [comment]
ping

**Comment by nadako** [comment]
This is now deployed thanks to @andyli
