### ISSUE TITLE
Request to remove library on lib.haxe.org

### ISSUE THREAD

**Issue by jv-PintoBobcat** [HaxeFoundation/haxelib#237]
I submitted a library called ajax in error.  Can you please delete it?

http://lib.haxe.org/p/ajax/

**Comment by jv-PintoBobcat** [comment]
Any movement on this?  I sent an email to contact@haxe.org about this issue as well and I haven't received a reply.

**Comment by jasononeil** [comment]
Hi there.  I've got access to the database so I've gone ahead and deleted this.  Sorry for the delay.

We really need to set up a way to delete your own projects... I'll try look into it soon.

**Comment by jv-PintoBobcat** [comment]
Thank you!
