### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by mathieuanthoine** [HaxeFoundation/haxelib#239]
It could be great to have the possibility of changing the password when we forgot it.

Thanks

**Comment by TBaudon** [comment]
Yep,
I forgot my password as well, must have made a typo twice when initializing account >.>

Could someone please reset my password ? I'm http://lib.haxe.org/u/TBaudon/ .
Thanks!

**Comment by andyli** [comment]
Sorry for the delay. If you still want to change the password, please send me an email (can be found on my profile) with:
 1. your haxelib user name
 2. the md5 hash of your new password
