### ISSUE TITLE
haxelib setup changed default location to /usr/lib/haxelib

### ISSUE THREAD

**Issue by jasonsturges** [HaxeFoundation/haxelib#242]
Was it intended for haxelib to change the default location, as in upon executing:

    $ haxelib setup
    Please enter haxelib repository path with write access
    Hit enter for default (/usr/lib/haxelib)

In 3.1, this location was: `/usr/lib/haxe/lib`

In 3.2, this location is now: `/usr/lib/haxelib`

Moving forward, should `/usr/lib/haxelib` be used as the convention?

**Comment by leshido** [comment]
Please note that the default location is unwritable on latest Mac OS X El Capitan. Posted an issue on #250 . Default location should probably be `usr/local/lib/haxelib`.

**Comment by nadako** [comment]
This actually looks like a bug introduced in 11d4b7b98b1a3b611728d5ce32c636abe62546ed (note the missing slash). Am I right, @waneck?

**Comment by waneck** [comment]
Oops. Indeed it was.
But anyway on the mac we need to default for `/usr/local/lib/haxe` because `/usr/lib` is not writable there anymore

**Comment by nadako** [comment]
So #258 is good to merge (after fixing slashes of course)?

**Comment by waneck** [comment]
Yes

**Comment by nadako** [comment]
Thanks!
