### ISSUE TITLE
haxelib allows upgrade to succeed with insufficient disk space

### ISSUE THREAD

**Issue by triplefox** [HaxeFoundation/haxelib#244]
Observed: ran "haxelib upgrade lime". lime-2,6,1.zip was downloaded. In the midst of unpacking and copying the files haxelib aborted with a generic syscall exception. FlashDevelop noticed that the disk had run out of space by this point. I freed up space, however, the new lime was partially installed now and haxelib would not let me fix it through its UI. I resorted to deleting the directory manually and rerunning haxelib.

**Comment by ibilon** [comment]
Not just for that error.
Once the installation start if there is any error the installation isn't canceled.

**Comment by nadako** [comment]
This will be covered by #267
