### ISSUE TITLE
sort versions properly

### ISSUE THREAD

**Issue by raould** [HaxeFoundation/haxelib#245]
e.g.
```
openfl: 3.1.2 3.2.0 3.1.3 [3.3.3] 2.2.4
```
should preferably display as
```
openfl: 2.2.4 3.1.2 3.1.3 3.2.0 [3.3.3]
```

**Comment by nadako** [comment]
Latest haxelib version used in haxe/development seems to sort properly:

```
openfl: 2.2.4 3.3.2 3.3.3 3.3.4 [3.4.0]
```

**Comment by Gama11** [comment]
Somehwat related: #228

**Comment by nadako** [comment]
I'll look at the code whether it's fixed or not, but anyway this is a duplicate of #83
