### ISSUE TITLE
Request to remove emitter lib on lib.haxe.org

### ISSUE THREAD

**Issue by R3D4C73D** [HaxeFoundation/haxelib#248]
I'd like my library "emitter" removed as soon as possible.  Thank you.

http://lib.haxe.org/p/emitter/

**Comment by back2dos** [comment]
Could you please explain why?

We do remove libraries that were published by mistake, but this seems like
it is published on purpose and may be in use by other Haxers.

**Comment by jv-PintoBobcat** [comment]
I don't want to have to maintain it anymore.  And I doubt anyone is going to miss it with the grand total of downloads being zero.

**Comment by ibilon** [comment]
The download counter is broken. And it being only doesn't require you to maintain it ;)

**Comment by jv-PintoBobcat** [comment]
Fair enough.  The code repo is now private, but the packaged version can remain, I guess.

**Comment by jv-PintoBobcat** [comment]
Actually, I just want it off of there because I don't want it associated with the xod3 account any more.  I have abandoned both the account on haxelib and the account on bitbucket.  Is there a way I can get it associated with my github account or something?

**Comment by jv-PintoBobcat** [comment]
Or can it just please be removed?  I'm afraid I have to insist.

**Comment by Simn** [comment]
Let's remove it in this case.

I'm curious though if the author insisting on removal has any bearing in the general case.

**Comment by jv-PintoBobcat** [comment]
Any movement on this?

**Comment by jv-PintoBobcat** [comment]
Any movement on this?

**Comment by andyli** [comment]
Sorry for the delay, but at least I've just removed it.
