### ISSUE TITLE
compiler -lib: ignore .dev if library version specified

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxelib#249]
I think, if a library version specified then dev library version must not be used:
```cmd
haxe -lib mylib:1.0.0 ...
```
So, file `.dev` must be ignored by compiler in this case.

**Comment by ibilon** [comment]
Doesn't that removes the override purpose of dev?
If the version is used then dev is only used when there's no version and becomes just a set.

**Comment by Simn** [comment]
I think having it as explicit > dev > set makes sense.

**Comment by ibilon** [comment]
I like both approaches,
when you want a version you should get it,
but the override is useful too.

And that is a breaking change, if people upgrade haxelib their compilation will change,
for instance this wouldn't work anymore https://github.com/HaxeFoundation/haxe.org/blob/staging/.travis.yml#L22-L27

**Comment by ibilon** [comment]
bump @nadako do you think that this breaking change is okay? I think a lot of people rely on it.

Maybe it would be better is set could accept a directory, the set version/path would be used if no version/path is specified, unless a version/path is fixed by dev.

**Comment by nadako** [comment]
Eh... I don't really have an opinion on this.

Using `dev` mode as an override for everything (as it was before) doesn't sound nonsensical either.

I can guess that the original author's problem takes roots from the fact git/hg checkouts abuse `dev` mode and implicitly create `.dev`, which I find really stupid and I think should be changed (see #263).

**Comment by ibilon** [comment]
I vote for reverting to the previous behavior for now,
probably a lot more people rely on the override than people wanting to mix git version and normal version,
and later fix the git/hg dev usage in an update.

**Comment by yar3333** [comment]
My original problem is to have a ways to:
1. use recent (`.dev`) libs for active projects (via `-lib name`);
2. use old versions for legacy projects (via `-lib name:ver`).

Can we found another way to solve problem and prevent breaking old behavior?

**Comment by nadako** [comment]
@yar3333 have you considered using local repos (`newrepo`) for that?

**Comment by yar3333** [comment]
@nadako I don't hear about `newrepo` before. It can be solution. Sorry, I don't find any docs about this feature.

**Comment by nadako** [comment]
Yeah it wasn't really documented and was marked as experimental, but I think people should start using it. We've added [some documentation](https://github.com/HaxeFoundation/haxelib/blob/development/www/documentation-files/using-haxelib.md#newrepo) for the next version.

So, I'm gonna revert the behaviour and docs then...

**Comment by yar3333** [comment]
@nadako Thank you!

**Comment by tobil4sk** [comment]
Just for the sake of keeping track, this ended up being changed again (only for path and libpath) in: 634289105d8c5aee68768f664aeabb0a8fcab62d
