### ISSUE TITLE
[MacOS X El Capitan] haxelib setup default location is unwritable

### ISSUE THREAD

**Issue by leshido** [HaxeFoundation/haxelib#250]
Running `haxelib setup` suggests to install on default location `usr/lib/haxelib` which is, as of Mac OS X El Capitan, unwritable due to the new "Rootless" feature.

It should probably point to install on the writable location `usr/local/lib/haxelib`.

**Comment by andyli** [comment]
BTW, I would suggest changing the default haxelib repo location for all OS to `~/haxelib`.
It is annoying in Linux that running `haxelib install` requires the use of `sudo`...
But we have to think about `haxelib upgrade`, which will tie haxelib to the local repo... I mean haxelib is installed system-wise, so it should not use a user directory (`~/haxelib`).

Any comment, @back2dos, @ncannasse ?

**Comment by jangdan** [comment]
This isn't important, but this issue was also mentioned here:
https://github.com/HaxeFoundation/haxe/issues/4585

**Comment by lewislepton** [comment]
@andyli so just to ask - on doing say `haxelib setup` have instead of `/usr/lib/whatever` - have this instead `~/haxelib`

i just want to make sure before going ahead with installing haxe. since the 3.2.1 install on `/usr/local/lib/whatever`

cheers

**Comment by waneck** [comment]
I'd also prefer to have a local haxelib by default as well. It's more secure also.

**Comment by lewislepton** [comment]
just annoying apple do this with each OS they bring out. taking away the ability to do things. annoying to say the least - bring back snow leopard ;)

**Comment by lewislepton** [comment]
i guess i dont fell comfortable installing on `usr/local/etc`

but if its fine or better doing it in `~/haxelib` - then ill do that then. but dont know if it is until someone says ;)

**Comment by ibilon** [comment]
The necessity to use sudo to install to `/usr/lib` isn't annoying, it's normal. Most likely you only think that way because you're the only user on your computer, but in that case there's no reason to use that location.

The discussion of having the default location of haxelib in `~/haxelib/` hides another problem: the fact that haxelib can't make a difference between local and global install.

**Comment by lewislepton** [comment]
@ibilon so is it ok to do the install on `~/haxelib`? i just want to make total sure because i have a fresh computer waiting ;)

also would i just use 3.2 or 3.2.1 of the haxe installer?

thanks ;)

**Comment by ibilon** [comment]
@lewislepton sure, I've been using such a path for a while without problem
If you use the 3.2 installer you'll get haxe 3.2, if you use the 3.2.1 you'll get haxe 3.2.1,
since it's better to use the latest patch you should use the 3.2.1 installer.

**Comment by lewislepton** [comment]
@ibilon cool spot. cheers. in the end it does make sense. though a shame the word has to go out because more likely people have been comfortable with what it was using before

cheers ill get on and install fresh to `~/haxelib` ;)

**Comment by lewislepton** [comment]
i guess the difference in using `~/haxelib` is that it shows in the directory, as in its not hidden. or at least i have that myself
would be nice if it was hidden in some way

**Comment by ralcr** [comment]
This  is still not fixed, i think is not good to have it in the installer like that.

**Comment by nadako** [comment]
What about `/usr/lib/haxe/lib`? It was used before, but then was accidentally changed to `/usr/lib/haxelib` (see #242).

**Comment by MarkehMe** [comment]
On macOS it makes sense to put it in `~/Library/haxelib`
