### ISSUE TITLE
is the install counter on lib.haxe.org working?

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxelib#253]
Subj. Because e.g. for hxnodejs it shows 0 installs, though I downloaded it myself at least once.

**Comment by markknol** [comment]
@jasononeil @ncannasse bump.

What is needed to fix this? I can imaging it's very discouraging for library authors to see the download count stay the same. See http://lib.haxe.org/search/?v=hxnodejs

**Comment by ibilon** [comment]
So not all version of the library can have their counter increase,
and I get a `invalid field access : index` if I trace the error,
tacked it to https://github.com/HaxeFoundation/haxelib/blob/development/src/haxelib/server/Repo.hx#L319-L326

**Comment by markknol** [comment]
You will never notice because the function seems to be try/catched https://github.com/HaxeFoundation/haxelib/blob/development/src/haxelib/client/Main.hx#L769

**Comment by nadako** [comment]
This seems to be related to the `preview`/`previewNum` being null and passed to the SPOD query. Gotta dig into SPOD for that.

**Comment by ibilon** [comment]
Well if you're ok with hacks you can do:
```haxe
var version = SemVer.ofString(version);
var vl = Version.manager.search(
	$project == p.id &&
	$major == version.major &&
	$minor == version.minor &&
	$patch == version.patch
);

var v = null;
for (ve in vl)
	if (ve.preview == version.preview && ve.previewNum == version.previewNum)
		v = ve;

if( v == null )
	throw "No such Version : " + version;
v.downloads++;
v.update();
p.downloads++;
p.update();
```

work, but that's sad to do part of a select manually.

**Comment by nadako** [comment]
It generates wrong query expression for the enum, it doesn't respect that it's nullable and tries to get Type.enumIndex(preview) which fails with the invalid field access. This may be related to 6d41c431e4d3056d4a8269c4aedc46acb408cafe

**Comment by nadako** [comment]
> Well if you're ok with hacks you can do

another version is to construct the SQL manually, but I'd like to look into fixing RecordMacros first

**Comment by nadako** [comment]
I cherry-picked the fix to the master branch which should be auto-deplyed from Travis, let's see if it works...

**Comment by nadako** [comment]
It works \o/

**Comment by markknol** [comment]
This is great! Is it online yet?

**Comment by nadako** [comment]
Yeah it's online!

**Comment by markknol** [comment]
It works, I tried with a lib that had no downloads yet, now it has 1.

**Comment by markknol** [comment]
Are installs from CI also count as download count? Can we exclude them? Otherwise it might be a bit unfair.

**Comment by nadako** [comment]
We could check for travis/appveyor/whatever env vars and skip invocation of `postInstall`
