### ISSUE TITLE
[site] Readme.md formatting: table

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxelib#254]
Incorrect table formatting on lib.haxe.org. [Example: lib.haxe.org/p/hxnodejs](http://lib.haxe.org/p/hxnodejs/4.0.0/).

On the Haxelib:
![now terrible](https://cloud.githubusercontent.com/assets/888526/11268613/b9677d42-8ec2-11e5-8178-a20537727350.png)

On the Github:
![original](https://cloud.githubusercontent.com/assets/888526/11268628/c6fa0b64-8ec2-11e5-8253-a7efef129f76.png)

related issue: #226 .

**Comment by jasononeil** [comment]
Yep, this is a Haxe-markdown problem.  The workaround is to put a space in the dividing line:

So this works:

```md
| module            | status | comment                  |
| ----------------- | ------ | ------------------------ |
| assert            | done   |                          |
| Buffer            | done   |                          |
| child_processes   | done   |                          |
```

but this is broken:

```md
| module            | status | comment                  |
|-------------------|--------|--------------------------|
| assert            | done   |                          |
| Buffer            | done   |                          |
| child_processes   | done   |                          |
```

Thanks for creating the issue over on the other repo, I'll close this one now.

**Comment by nadako** [comment]
May I suggest simply using [pandoc](pandoc.org) to do the markdown->html conversion? It's a nice single-file utility written in Haskell that supports many file formats, including GFM and full CommonMark ("proper" markdown spec with tables, code fences and so on), and it's really easy to use:

```haxe
class Main {
    static function main() {
        var src = "
header1 | header2
--------|--------
content1|content2
";

        var proc = new sys.io.Process("pandoc", ["-f", "markdown", "-t", "html"]);
        proc.stdin.writeString(src);
        proc.stdin.close();
        proc.exitCode();
        var result = proc.stdout.readAll().toString();
        proc.close();

        trace(result);
    }
}
```
outputs:
```html
<table>
<thead>
<tr class="header">
<th align="left">header1</th>
<th align="left">header2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">content1</td>
<td align="left">content2</td>
</tr>
</tbody>
</table>
```

**Comment by fzzr-** [comment]
:+1: , especially because currently used Haxe-markdown is not fully stable & suitable for serious production as a dependency. [:(](https://github.com/dpeek/haxe-markdown/issues)
