### ISSUE TITLE
Extension Removal

### ISSUE THREAD

**Issue by fbricker** [HaxeFoundation/haxelib#261]
Hi, we've been renaming some extensions and I'll like to remove the old named extensions from haxelib.

The extensions I need to remove are:
* openfl-admob
* openfl-gps-lib
* openfl-share
* openfl-gpg
* openfl-locale
* openfl-webview
* openfl-nativedialog

The new extensions (in case you can forward extensions names) are:

* extension-admob (replaces openfl-admob)
* extension-googleplayservices-lib (replaces openfl-gps-lib)
* extension-share (replaces openfl-share)
* extension-googleplaygames (replaces openfl-gpg)
* extension-locale (replaces openfl-locale)
* extension-webview (replaces openfl-webview)
* extension-nativedialog (replaces openfl-nativedialog)

Thanks!!!

**Comment by Simn** [comment]
Why go for a general name like this for something that's OpenFL-specific?

**Comment by nadako** [comment]
+1

**Comment by fbricker** [comment]
OpenFL community decided to name extensions this way.
Anyway, those are not openfl-specific (they also works with NME and may work with other engines using HXCPP / supporting JNI with little changes).

**Comment by nadako** [comment]
So, what's the process here? Who takes this kind of decisions? I think we have to come up with some policy regarding that and document it.

**Comment by fbricker** [comment]
I don't think there's actually someone taking this kind of decisions (it was just a quick chat inside a group and someone came up with the idea of adding the word extension- as a prefix, for OpenFL/NME and Lime extensions, and we all agreed on that without much discussion).

Anyway, I think it's a good idea to put some rules into haxelib (not only for naming, but maybe also for quality). It'll also be nice to have some trusting mechanism that can let people know which libraries are trustworthy and which ones are not. 

On my case I'm open to adapt my libraries to any standard proposed by the HaxeFoundation :+1: 

In the meantime: What should I do with my deprecated extensions? (for the time being, I just uploaded new empty versions that raises an error telling people that those are deprecated, but I think it'll be nice to remove them to keep haxelib clean). Just an idea.

**Comment by ibilon** [comment]
I think @nadako meant who takes the decision for haxelib, who choose what to remove, rename ...

**Comment by nadako** [comment]
Yup I meant haxelib policy.

**Comment by fbricker** [comment]
Oh, in that case I don't know... I just asked Nicolas how to remove libs from haxelib and he told me to open an issue here since Andy Li will soon take over haxelib maintenance.

**Comment by nadako** [comment]
ping @andyli

**Comment by andyli** [comment]
See https://github.com/HaxeFoundation/haxelib/issues/168#issuecomment-240850368.
Since the old libs are deprecated properly already, I will close this issue.
