### ISSUE TITLE
[Github] Add tags & priority-tags for issues

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxelib#273]
Need create tags ("Labels") , priority-tags & feature-tags same as in the Haxe repository and [TiVo](https://github.com/TiVo/intellij-haxe/issues) (e.g.: [`bug`](https://github.com/HaxeFoundation/haxe/labels/bug), [`feature-completion`](https://github.com/HaxeFoundation/haxe/labels/feature-completion), [`Priority N`](https://github.com/TiVo/intellij-haxe/labels/Priority%202)).

**Comment by nadako** [comment]
Let's add these when we need some. The issues process in haxelib is a bit different right now, and IMO we already have the labels we need, e.g. `support`, `website`, `client`, `bug`, `enhancement`. I'd actually remove several ones, like `invalid`, `accepted`, `codereview`.

**Comment by fzzr-** [comment]
I think this issue has bin written before labels was added to the repo.
