### ISSUE TITLE
Dependencies per target in haxelib.json

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxelib#275]
In the `haxelib.json` of Flambe this line exist. 
```json
  "dependencies": {
    "air3": "",
    "hxsl": "2.0.5"
  }
```
This means you need these libraries to compile the project. But both projects are for the swf-target.

I mostly use the JavaScript-target of Flambe. I still need air3 to be installed. Can I define a rule that I only need certain haxelib when compiling to swf-target?

**Comment by ncannasse** [comment]
Dependencies are installed when installing the library, not when compiling so you will have to install air3 anyway. Should it be excluded from compilation parameters when compiling for something else that JS? maybe, but I'm not sure how to do that.

**Comment by markknol** [comment]
Exactly, but the compilation fails if I don't have it's dependencies installed, and I only have `-lib flambe` added to the project.
``` Error: Library air3 is not installed : run 'haxelib install air3' ```
