### ISSUE TITLE
Set hxcpp to version 3.2.205 [y/n/a] ? n

### ISSUE THREAD

**Issue by smks** [HaxeFoundation/haxelib#276]
Prompts to update hxcpp to a previous version even though I have the latest applied.

haxelib upgrade
...
Set hxcpp to version 3.2.205 [y/n/a] ? n
....

haxelib list
hxcpp: 3.2.102 3.2.171 3.2.180 3.2.193 3.2.205 [3.2.94]

**Comment by ibilon** [comment]
It is a newer version, patch 205 > patch 94,
the listing isn't in the right order.

Fixed but not yet deployed (https://github.com/HaxeFoundation/haxelib/issues/83), same for the website (https://github.com/HaxeFoundation/haxelib/issues/236)

**Comment by smks** [comment]
Is this still not deployed? Still keeps setting it to previous version and breaking build.
hxcpp: 3.2.102 3.2.171 3.2.180 3.2.193 [3.2.205] 3.2.94

**Comment by ibilon** [comment]
The website was deployed but not the tool,
3.2.205 is still the latest though,
do you mean that it changes on its own?

**Comment by smks** [comment]
![image](https://cloud.githubusercontent.com/assets/4087157/13381233/e60d5d68-de4e-11e5-802e-860af4a74183.png)

When I run haxelib upgrade, it tries to set version as 3.2.205 when in fact it should be 3.2.94

**Comment by ibilon** [comment]
No no, hxcpp 3.2.205 was released after 3.2.94,
205 > 94
it's the list that's not in order.

3.2.94 : 2015-05-11
3.2.205 : 2015-12-24
there's even 4 versions between them
http://lib.haxe.org/p/hxcpp/versions/

**Comment by smks** [comment]
Oh right, I thought it was an old version as when I try and build with hxcpp I get:
`Library hxcpp version 3.2.205 does not have a run script`

**Comment by smks** [comment]
Seems to be a known issue https://groups.google.com/forum/#!topic/haxeflixel/1Sor7iv7c5w

**Comment by nadako** [comment]
Ehm, I guess hxcpp 3.2.205 has been reuploaded with a run script. Anyway, this is not a haxelib issue.
