### ISSUE TITLE
Site deployment

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxelib#277]
I've just [updated](https://github.com/HaxeFoundation/haxelib/commit/80584ddf1daa3e7f2ea2bea20afe46c6a7c603ec) something. How can I get it deployed?

@jasononeil @ncannasse @back2dos @nadako @andyli

**Comment by nadako** [comment]
There are also some undeployed fixes like #212, #59, #221, #236 and probably more. I would like the deployment process to be at least documented, or better yet, somehow automated.

**Comment by andyli** [comment]
I'm willing to work on the automation once I've haxelib server access (I don't have yet).

**Comment by ibilon** [comment]
A reminder that for #221 we need a cache clear in ufront in case that's not automatic when deploying.

**Comment by back2dos** [comment]
For the API, you will have to replace the index.n in `/api/3.0` or something. For the site, I don't know.

**Comment by nadako** [comment]
There's some [deploy.json](https://github.com/HaxeFoundation/haxelib/blob/master/deploy.json) file, but i don't know how it's used.

**Comment by nadako** [comment]
Somewhat related to deployment: #56

**Comment by ncannasse** [comment]
@jasononeil has been taking care of the deployment. Jason, could you get in touch with Andy so he can get access?

**Comment by andyli** [comment]
I've just deployed a new version. Please check if everything is working correctly.
I'll config Travis to auto deploy, but we should have good test coverage first to prevent careless commits annoying the whole haxe community.

**Comment by nadako** [comment]
Maybe it would make sense to only deploy if the commit message contains some special instruction like `[ci-deploy]`.

**Comment by ibilon** [comment]
Or use the master/development branches system.

**Comment by andyli** [comment]
@nadako @ibilon Good ideas!
I will use master/development branches as it is similar to the haxe repo.

**Comment by nadako** [comment]
Nice!

**Comment by andyli** [comment]
Done ;)
