### ISSUE TITLE
Available version check

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxelib#282]
I'm pretty sure (from experience) that most people don't know about self-update and end up using the bundled haxelib until the next haxe version.

We should really indicate to the user when a new version of haxelib is available.
```
A new version (X.Y.Z) of haxelib is available.
Do "haxelib selfupdate" to get the latest version.

/normal output/
```

The test would be quick, getting something like `http://lib.haxe.org/latestVersion/haxelib` which would contain only the semver (so very light).
It would be at least on the commands that already connect to the internet, and we should probably cache the result too.

That way we can really send bug fixes and improvements.

I think it's important to ship that feature with haxe 3.3.

**Comment by nadako** [comment]
Good idea! Though I think it would be easier to implement a method in SiteApi instead of a http request.

**Comment by ibilon** [comment]
Forgot about that but yes.

**Comment by ncannasse** [comment]
Sounds like a good idea, but not on "path" please :) (used for every compilation)

**Comment by nadako** [comment]
Yeah, as discussed and implemented in #283, it's done only for `net` commands

**Comment by nadako** [comment]
Done in b779136d257be75aa8b839d9f92c44bd9b56ab1b (BTW @ibilon: you can use `closes #<issuenum>` in commit messages to automatically close issues when it gets merged)

**Comment by ibilon** [comment]
I know, just completely forgot about this issue even though I opened it :)

Thanks for closing it.
