### ISSUE TITLE
Deprecation of command

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxelib#288]
Following https://github.com/HaxeFoundation/haxelib/pull/283#issuecomment-194972583

I think these three commands should be deprecated:
- selfupdate
- local
- either update or upgrade (and update the help message of the other)

Deprecation would mean to hide them from the help and show a notice when running them:
`Warning: this command is deprecated, use "$replacement" instead, and will be removed in a later version.`

Here `$replacement` would be (respectively):
- `haxelib update haxelib_client`
- `haxelib install file.zip`
- either `haxelib upgrade library` or `haxelib update`

And the later version would most likely be the one released with haxe 4.

And while we are on the topic of hiding things I don't think we should show the entire help when haxelib is run without arguments, only the common things.

Things like: config, path, convertxml, newrepo, deleterepo, proxy, all flags but always could only appear when doing `haxelib help`.
With that and the deprecated command the output would go from the currently long 38 lines to 25.

**Comment by nadako** [comment]
Note that `upgrade` and `update` commands were unified in bfcd9cae2a4b368fa00eb8a1ce6fc4b2bf5e8fb3 and I think we can keep it this way, it's just handy not to care whether you type `update` or `upgrade`.

**Comment by nadako** [comment]
Not sure I understand you now :) `upgrade` is already hidden, for others what you propose seems good: emit a warning, maybe add a `[DEPRECATED]` tag to their description.

**Comment by nadako** [comment]
Agreed!
