### ISSUE TITLE
haxelib client and haxe binary : The Value of HAXELIB_HOME environmental variable should be checked before ~/.haxelib file value 

### ISSUE THREAD

**Issue by zaxebo1** [HaxeFoundation/haxelib#29]
With reference to discussions at 
https://groups.google.com/forum/?fromgroups=#!searchin/haxelang/haxe$202$20and$203/haxelang/trmq-4H1J8g/_qA6Ox3uO3MJ

haxelib binary which currently reads ~/.haxelib file to decide for haxelib path. 
We should modify it such that "haxelib" binary and "haxe" etc bianries should first check for environmental variable HAXELIB_HOME (to point to haxelib path) and if it is not found only then it will look inside the file ~/.haxelib and so on.
The advantage will be that on the same machine and same login and we can have two simultaneous running two different haxe future versions pointing to two different directories using environmental variable.

FOR EXAMPLE: In case of java, i am demonstrating full workflow of simply running two java version (using environmental variables) SIMULTANEOUSLY:

````  
   I launch one xterm/gnome-terminal/konsole/console
           export JAVA_HOME=/opt/jdk1.5                                 #so all the java runtime platform .jars will be pulled out of jdk 1.5
           export PATH=$JAVA_HOME/bin:$PATH                      #so my java executable, javac executable and all other executables will be pulled out of jdk1.5
           javac   Hello1.java                                                        #so jdk1.5's  javac executable is compiling using jdk1.5 libraries  (compilation time)
           java   -cp . Hello1                                                        #so jdk1.5's  java executable is running the class file using jdk1.5 libraries   (runtime) . It may be running as 24 hour running monitoring program(say) .


   Without closing the first xterm ; now   I launch second xterm/gnome-terminal/konsole/console
         export JAVA_HOME=/opt/jdk1.7                                 #so all the java runtime platform .jars will be pulled out of jdk 1.7
         export PATH=$JAVA_HOME/bin:$PATH                      #so my java executable, javac executable and all other executables will be pulled out of jdk1.7
         javac   Hello2.java                                                        #so jdk1.7's  javac executable is compiling using jdk1.7 libraries  (compilation time)
         java   -cp . Hello2                                                        #so jdk1.7's  java executable is running the class file using jdk1.7 libraries   (runtime). It may be running as 24 hour running monitoring program(say).
````

So we have two simultaneously running java programs running on different versions of JDK in different terminals on SAME machine at SAME INSTANT inside the same user (non-root).

In the same way, HAXELIB_HOME environmental variable will point to haxelib path.
This will also help in keeping the entire haxe library and haxe binary on a portable usb pen drive without touching any single file in users directory.

**Comment by back2dos** [comment]
Jason, do you feel like looking into this or closing it? It's time to regain the upper hand! ;)

**Comment by zaxebo1** [comment]
please do it. It will facilitate multiple installation of **multiple different versions of haxe (say, one latest "stable" release, another currrent git version )** working in two different gnome-terminal , by setting two different environment variable. 
This is really essential.

**Comment by jasononeil** [comment]
Yeah I think it's worth having.  I saw Nicolas committed a change which involved a hidden ".haxelib" directory, but I haven't looked into it yet.  I'll schedule some time to do some haxelib work at the end of the week.

**Comment by zaxebo1** [comment]
:+1: 
 wow. It will be great to have this feature finally, before impending haxe 3.2 version release. 

Because then i can have "3.1" (as it is old stable) , "3.2" (as it is forthcoming stable), and as always latest git version - all running on my machine and server in a far cleaner way, this time.

**Comment by nadako** [comment]
Wait, isnt HAXELIB_PATH already implemented?

**Comment by back2dos** [comment]
Just a few weeks back I have heard it doesn't work in another issue. And also the more extensive search that Jason laid out above is not implemented.

**Comment by ncannasse** [comment]
We have a way to have a per-project repository, which I think is better than having to switch per-terminal environment variable

**Comment by zaxebo1** [comment]
@back2dos :  yup, you are right.
     "currently" HAXELIB_PATH many a times does not work correctly for haxe-compiler and haxelib both.

**Comment by jasononeil** [comment]
So, @nadako is correct.  "HAXELIB_PATH" is already implemented, we just need to release a new version.  As for the "more extensive search", Nicolas' approach is better.  Is there any reason you have commented it out @back2dos?

@ncannasse commit: 5c5e885c0edd2fd3d5773cb98af337ce17057233
@back2dos revert: 5d201e66ed6758e60700b817495db1ee83fe2906 

If we put it back in (uncomment it) then the logic / priority currently is:

1. Local ".haxelib/" directory for this project.
2. HAXELIB_PATH environment variable with path to haxelib repo
3. "$HOME/.haxelib" text file with the path to haxelib repo
4. "/etc/.haxelib" text file with the path to haxelib repo
5. On Windows, "$HAXEPATH/lib/" if it exists

Which I think will work for pretty much everyone.

**Comment by jasononeil** [comment]
I'm guessing you commented it out because it wasn't compiling, due to use of `FileSystem.absPath`, which didn't exist in 3.1.3, and has already been renamed to `absolutePath` for 3.2.

I've worked around that in the code (the function being called was only two lines anyway, only one of which we needed).  Once I push that I think we're safe to close this issue.

We'll need to make a note to document this in the manual too.

**Comment by jasononeil** [comment]
I've re-enabled the commands, but forgot to mention it in the commit message:

https://github.com/HaxeFoundation/haxelib/commit/0fed019b9c2e2aae22ff3007979737265753d54a

I renamed them to "newrepo" and "deleterepo", to prevent people being confused and thinking they start a new project or delete an old project or delete an installed library etc.

@ncannasse  if you feel there is anything unsatisfactory feel free to re-open the issue

**Comment by zaxebo1** [comment]
So, does it mean that ""now, i do not need to have sudo rights (that is, i do not need to use /usr/lib/haxe)  and also  i now can "compile haxe itself  from source" in my normal user(non-admin user) home directory itself and  also compile haxelib from source and use haxelib entirely in my user's home dir. Obviously this will also lead to parallel installations""

I will test this codecommit and report back , if any issues.

**Comment by jasononeil** [comment]
For me it means I can have a project in:

    /home/jason/workspace/ufront/hello/

And then when I run `haxelib newrepo` it creates:

    /home/jason/workspace/ufront/hello/.haxelibs

Now `haxelib install`, `haxelib path`, etc will all use that local directory.  No environment variables or setup files needed.  There are some disadvantages (having to download libraries more than once) but overall the advantages of separate repos for each project outweigh the disadvantages.

**Comment by back2dos** [comment]
I commented it out, because it didn't compile and because I had plans to replace it by a behavior not that quirky. What I mean by that:

1. I have reservations about it: https://github.com/HaxeFoundation/haxelib/issues/141#issuecomment-66418541
2. it introduces behavior that we will have to support in the future. Duplicating libraries all over the place is not something I am very fond of. This project is already so full of questionable decisions, I'd rather not add to the problem.
3. Specifying exact dependecies in your hxmls + `haxelib install all` gives you project local setup, without any of the issues I raised.

I have voiced my concerns. I didn't get around to fixing the stuff myself and I'd really rather not commit to this behavior. This deserves a better solution and I don't look forward to people being upset when we break their setup by rolling it out. I'd rather fix the current defects, particularly selfupdate and then we can still roll this out whenever we want.

But if you feel we should go ahead with it for 3.2. I'm not going to stop you. In that case, please close #141.

**Comment by ncannasse** [comment]
@back2dos I'm fine with any counter proposal when it's backed with an intention to actually contribute an implemention. We have been discussing local repos for a long time and nobody has yet even experimented with it. My solution is maybe not perfect but it works pretty well and is quite simple to understand for the end user.

We stil need to adress the selfupdate issue, but let's maybe open an separate issue for it

**Comment by zaxebo1** [comment]
after testing , it is working fine , the way i needed. thanks
