### ISSUE TITLE
deleterepo doesn't ask for confirmation

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxelib#297]
As title says,

unlikely you'd do that by accident by still.

Also newrepo doesn't say anything like `Local repository created in $(pwd)`,
and doing it a second time doesn't warn you.
deleterepo doesn't print anything either.

**Comment by nadako** [comment]
That it doesn't ask is consistent with `haxelib remove`, I'd say. Plus as you said it's unlikely to do by accident, so I haven't implemented that. I added some output to these commands. Not sure about wording though.
