### ISSUE TITLE
lib.haxe.org: pictures embedded via relative paths don't work

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxelib#300]
This picture at the top of the Flixel readme (http://lib.haxe.org/p/flixel/) doesn't show up:

![](http://i.imgur.com/Sn0UeYo.png)

It's embedded like this:

```
[![](showcase.png)](http://www.haxeflixel.com/showcase)
```

`showcase.png` is part of the repo's root directory.

**Comment by nadako** [comment]
This is probably not an easy fix, but we may look into it

**Comment by Simn** [comment]
Should we really support that? It would mean hosting the unzipped images on our server.

**Comment by ibilon** [comment]
We do http://lib.haxe.org/p/flixel/4.0.0/files/showcase.png

**Comment by Simn** [comment]
Hmmmmm...

Well, since we're already doing that we might as well fix the URL.

**Comment by nadako** [comment]
Deployed and seems to work. I'm not sure if the code's good, since I know almost nothing about UFront.

**Comment by Gama11** [comment]
Nice! Not used to haxelib issues getting fixed this quickly. ;)

**Comment by nadako** [comment]
Thank @andyli for the easy workflow - we just push to master branch and it magically appears on the website \o/
