### ISSUE TITLE
Properly document project-local repositories

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxelib#303]
It's weird that a large chunk of our README.md file describes a particular and non-essential use-case/feature. I think this should be moved away to the [documentation directory](https://github.com/HaxeFoundation/haxelib/tree/development/www/documentation-files) and appear on the web-site.

**Comment by nadako** [comment]
While the text @back2dos wrote here is well-written and informative, I feel like it belongs more to some kind of tutorial or a blog post, for which we don't have a specific place in haxelib repository.

Also, some information is a bit redundant now when we have a [full documentation](https://github.com/HaxeFoundation/haxelib/blob/development/www/documentation-files/using-haxelib.md) for the haxelib CLI.

Any opinions? If none follow, I think I'll just remove it from the README.

**Comment by andyli** [comment]
Yes, I think we should just move the important info to using-haxelib.md and remove that README section.

**Comment by back2dos** [comment]
Agreed, this should be in the on-site documentation. And the README should
refer there, too.

**Comment by markknol** [comment]
Closing since this is looks ok to me now.
