### ISSUE TITLE
Support libs from git in the build.hxml

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxelib#304]
So that it's easy to install forked libs when bootstrapping a project, something like:

```
-lib http://github.com/foo/bar.git:master
```

where master can be a tag or a branch.

Then one can just run `haxelib build.hxml`, instead of installing each lib manually.

What do you guys think?

**Comment by Simn** [comment]
-lib doesn't, and shouldn't, install anything. Let's not make this unnecessarily complicated by mixing up installation and usage steps. If anything this should be part of `haxelib install all`.

**Comment by fullofcaffeine** [comment]
Cool, thanks Simon.

**Comment by fullofcaffeine** [comment]
Actually, as a reference, this issue describes the original idea behind this: https://github.com/HaxeFoundation/haxelib/issues/238. 

Good to know it's being discussed already!
