### ISSUE TITLE
Versions page: newest version should be on top

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxelib#306]
On http://lib.haxe.org/p/lime/versions/ for example, you have to scroll down quite a bit to get to the current version. That seems counter-intuitive, I think the sorting should be inverted.

**Comment by Simn** [comment]
Agreed

**Comment by nadako** [comment]
Deployed :)

**Comment by Gama11** [comment]
That was definitely a lot quicker than expected! :+1:
