### ISSUE TITLE
Files page: extremely long dropdowns with many versions + sorting

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxelib#307]
http://lib.haxe.org/p/lime/2.9.0/files/

The sorting here should probably match the new changes from #306.

Also, there should probably be a max height, otherwise the dropdown can go beyond the footer, which looks a little silly:

![](http://i.imgur.com/0zOstQ1.png)

**Comment by markknol** [comment]
This is fixed, it has a scrollbar now
