### ISSUE TITLE
missing the source of www/js/*.js

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxelib#310]
Look like `www/js/app.js` and `www/js/client.js` are compiled from Haxe, but I couldn't find their source...
I suspected they were missed in @nadako's [import](https://github.com/HaxeFoundation/haxelib/commit/04c48a2cfcfb6777b6fe5eeadb1d8167ef84e13f), so I checked out the [original development repo](https://github.com/jasononeil/haxelib/tree/feature/newsite), and found that there is a hxml that produce `www/js/client.js`, sits in `submodules/ufront/submodules/hello/client.hxml`... (what?)
A quick search didn't return me the hxml of `www/js/app.js`...
I'm confused.

**Comment by nadako** [comment]
I looked at the code a bit and...

The `client.js` seems to be [something from haxe.org](https://github.com/HaxeFoundation/haxe.org/blob/master/src/BasicClient.hx).

The `app.js` seems to be compiled from https://github.com/ncannasse/hxtasks.

I wonder if they are used on lib.haxe.org at all.

**Comment by nadako** [comment]
Looks like `client.js` is referenced in templates to add some interactivity. We could probably just use one from `haxe.org`. Not sure about `app.js`...

**Comment by ncannasse** [comment]
app.js has most likely nothing to do there :) is it actually included/referenced somewhere?
