### ISSUE TITLE
Project page should show dependencies

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxelib#321]
The dependencies defined in the `haxelib.json` seem to be the only information not presented anywhere on a project's page.

It would be nice if they were part of the table on the right that shows other information from the `haxelib.json` like website, license or tags.

**Comment by nadako** [comment]
I don't have an opinion about showing dependencies on the project page, but one nice usage of that information is the "most depended-upon libraries" feature [similar to NPM](https://www.npmjs.com/browse/depended).

**Comment by markknol** [comment]
Done in https://github.com/HaxeFoundation/haxelib/commit/03950b5892e330f5722d7aab37bb68dbc69db69f

It would be nice if the data was in the database, then we could query a "most depended-upon libraries". at the moment I infer the dependencies from the haxelib.json from the zip, which isn't very nice but gets it sort of done.
