### ISSUE TITLE
Haxe highlighting used for everything on files page

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxelib#322]
It seems like every page on `/files` uses haxe highlighting:

``` html
<code class="prettyprint haxe highlighted">
```

While this is only slightly noticable for `.json` because urls are rendered as comments...:

![](http://i.imgur.com/fNaIbAl.png)

http://lib.haxe.org/p/flixel/4.0.1/files/haxelib.json

...xml files are hardly recognizable as such anymore:

![](http://i.imgur.com/midKdPM.png)

http://lib.haxe.org/p/flixel/4.0.1/files/include.xml

**Comment by nadako** [comment]
The json case is funny because json is valid haxe syntax.

**Comment by ibilon** [comment]
Wouldn't the url example also happen on haxe code? If that's the code from haxe.org there's only haxe, and a basic highlight for it.

**Comment by nadako** [comment]
Can't we just use https://highlightjs.org/ like every other kid?

**Comment by ibilon** [comment]
I can't find haxe support in it, having better (any) support for other languages sure, but it'd be sad if we didn't have haxe :)

**Comment by nadako** [comment]
It has haxe support. I use it in my blog: http://nadako.github.io/rants/posts/2016-03-05_haxe-import-hx.html

**Comment by markknol** [comment]
The highlighting is nicer now (probably not gama11-compliant™) and jsons dont get highlighted. 

It uses https://lib.haxe.org/p/html-haxe-code-highlighter/ atm.
