### ISSUE TITLE
Running site locally

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxelib#324]
I don't know what I'm doing wrong but I cannot load the site locally:

I first get this error:
![image](https://cloud.githubusercontent.com/assets/576184/14464442/190cc224-00cf-11e6-917f-e3732a4acb12.png)

and the log (and website in browser) log this:
![image](https://cloud.githubusercontent.com/assets/576184/14464634/e2a9566a-00cf-11e6-95b8-5c851b1842aa.png)

I have a empty database running, I don't have docker installed.

**Comment by nadako** [comment]
Works here! I think you need to install some version of MS Visual C++ Runtime.

**Comment by markknol** [comment]
Oh, so does neko use the MS Visual C++ Runtime?

**Comment by nadako** [comment]
I think it's the sqlite.ndll, or well, anything compiled with VC++

**Comment by markknol** [comment]
It seems i already have it? 
![image](https://cloud.githubusercontent.com/assets/576184/14465436/50ce963e-00d3-11e6-8ce8-5ef33306de52.png)

**Comment by markknol** [comment]
Ah found it;
![image](https://cloud.githubusercontent.com/assets/576184/14465551/a795ab74-00d3-11e6-8be7-c2f8952ce08e.png)

**Comment by nadako** [comment]
Lol :) No, there should be just a "vc++ runtime library" download somewhere on MS website

**Comment by andyli** [comment]
https://github.com/HaxeFoundation/haxe/issues/2008 ;)

Again, what's the problem with docker? It should be much easier to set up than mod_tora.

**Comment by markknol** [comment]
It still doesnt work. I installed the full 4gb of c++ tooling, and the dotnet 1.1 framework.

The problem with docker is that I don't understand how to install/use that?

Sorry maybe I'm just stupid but I don't understand how to get it up and running.

**Comment by markknol** [comment]
ok i forgot to copy the dll file. 

New thing; What do I need to do now?
```
Called from a C function
Called from (no debug available)
Called from haxelib/server/SiteDb.hx line 127
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/db/Mysql.hx line 203
Exception : Neko_error(mysql.c(508) : Failed to connect to mysql server : Failed to resolve host 'dbHost')
```

**Comment by andyli** [comment]
Setting up mod_tora on Windows is indeed non-trivial. That's the conclusion I made in the previous month after setting it up on AppVeyor. If you really want to do it, check what's done in appveyor.yml and RunCi.hx.

For docker, you just have to learn some basics by following the [get started guide](https://docs.docker.com/windows/).

**Comment by andyli** [comment]
> Exception : Neko_error(mysql.c(508) : Failed to connect to mysql server : Failed to resolve host 'dbHost')

update dbConfig.host to be "localhost", as done in https://github.com/HaxeFoundation/haxelib/blob/development/test/RunCi.hx#L87

**Comment by markknol** [comment]
Ok I give up this is too frustrating 

![image](https://cloud.githubusercontent.com/assets/576184/14467028/ad95cb48-00d9-11e6-8889-c1ac02b15891.png)

**Comment by andyli** [comment]
I just meant to look at RunCi... not actually run it..
Anyway, at least now you know how frustrating I felt last month. ;)

**Comment by markknol** [comment]
Ok well thanks andy. I'll try it at a different time again.

**Comment by andyli** [comment]
Ok, no problem.
I'm closing this for now. Feel free to reopen or find me on gitter when you want to have another try.
