### ISSUE TITLE
[SEO] Use project description in HTML meta and twitter description tags

### ISSUE THREAD

**Issue by vizanto** [HaxeFoundation/haxelib#328]
When haxelib tweets a new library release, there's a bit of changelog but underneath only a generic piece of text about Haxe:

<img width="693" alt="screen shot 2016-05-31 at 22 58 28" src="https://cloud.githubusercontent.com/assets/326263/15690369/7d89979c-2783-11e6-8195-989f62c16ca5.png">

I'd like to see information about the haxelib itself instead.

**Comment by ibilon** [comment]
I think a description field needs to be added here https://github.com/HaxeFoundation/haxelib/blob/development/src/website/controller/ProjectController.hx#L57

**Comment by vizanto** [comment]
When will this go live?  Still seeing general Haxe information in tweets.

**Comment by ibilon** [comment]
We need to update the master branch, cc @nadako

**Comment by vizanto** [comment]
Release early and often. That's the theory anyway ;)
Still no change on twitter.
