### ISSUE TITLE
new ufront releases wanted

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxelib#334]
I've just fixed the haxe 3.3 rc1 builds. They require 2 ufront lib updates:
 * https://github.com/ufront/ufront-ufadmin/commit/4558fe0bb3534cda53396bc3b4b099a867f5b6a6
 * https://github.com/ufront/ufront-uftasks/commit/1ef09322eb51cf5d16bc1f9abeecaeb30542b62f

@jasononeil Would you upload new haxelib releases such that we can depends on them instead of git versions? It would be great if you can add me, @kevinresol, or anyone in the HF to be one of the haxelib contributors in case we need this kind of minor release when you're away.

**Comment by jasononeil** [comment]
Thanks @andyli, I've deployed both now and added both you and @kevinresol as maintainers for these two libs.  I'll add you to the other ones as I push new versions.  

If you need any others urgently let me know :)
