### ISSUE TITLE
Binary run.n in repository

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxelib#338]
Does the binary run.n really have to be included in this repository?
Every time I compile my updated local repo run.n is recompiled (make haxelib is included in make all) and then `git status` reports "modified content" in the submodule extra/haxelib_src. No big deal, but seems a bit odd to include a binary here.

**Comment by nadako** [comment]
That is done so one could do `haxelib git haxelib https://github.com/HaxeFoundation/haxelib`. I know it's annoying, but I don't have another solution right now...

**Comment by mockey** [comment]
How about another client.hxml that compiles the binary to another name and is only used in the Makefile? A bit complicated maybe.
I'll try to work around this on my side, like renaming the binary before compilation and renaming it back afterwards...
