### ISSUE TITLE
--notrace Tag when installing packages.

### ISSUE THREAD

**Issue by eminfedar** [HaxeFoundation/haxelib#339]
Hi there,

We are using "**haxelib install package**" command for installing a package.
Sometimes I don't want to see thousands of traces during the setup.

Something like this can be awesome : "**haxelib install package --notrace**". And the silent install... :)

Can you add this feature to the haxelib?
Thanks!

**Comment by ibilon** [comment]
Latest haxelib doesn't print a package files by default anymore.
