### ISSUE TITLE
Remove Haxelib

### ISSUE THREAD

**Issue by ashes999** [HaxeFoundation/haxelib#341]
Hi, 

I semi-accidentally published [this haxelib](http://lib.haxe.org/p/qamar/0.1.0/) to lib.haxe.org. Could you please remove it?

Also, is there any way to validate my haxelib.json without running `haxelib submit`? I'm trying to get `haxelib dev foo .` to work with a local copy, and it keeps giving me a `could not find haxelib "foo"` error.

**Comment by andyli** [comment]
Removed.

For validating haxelib.json, I don't think we have a nice way for users to do it. But for now, you can `haxelib submit`, and when it asks for password, ctrl+c to terminate the submission. [According to our code](https://github.com/HaxeFoundation/haxelib/blob/3.3.0/src/haxelib/client/Main.hx#L523), `submit` will check the json (`Data.readInfos(zip,true)`) before asking for password, so it should work.

**Comment by ashes999** [comment]
I'll remember that for next time. Thanks.
