### ISSUE TITLE
Viewing the cross tag errors

### ISSUE THREAD

**Issue by skwerlman** [HaxeFoundation/haxelib#342]
When browsing to http://lib.haxe.org/t/cross, I get an error message:
`website.controller.HomeController.tag()`

All other tags (including empty/fake ones) work normally.

**Comment by anissen** [comment]
I also encountered this issue. "_cross_" is the most-used tag so I think it's important to fix.

![screen shot 2016-08-22 at 15 52 18](https://cloud.githubusercontent.com/assets/879967/17857016/7767ca12-6880-11e6-92e1-cd2f03677d86.png)

**Comment by nadako** [comment]
@ibilon looks like it's not quite fixed by your PR: `Invalid field access : toSemver`, could you look into this?

**Comment by ibilon** [comment]
Note: this affect http://lib.haxe.org/all too

The only reason this could happen should be because a project wasn't removed but all of its version were.

**Comment by ibilon** [comment]
It's now fixed.

**Comment by nadako** [comment]
Indeed!

**Comment by Gama11** [comment]
flixel seems to be missing from that page? There's only flixel-addons etc, but flixel core has the tag too, see http://lib.haxe.org/p/flixel/.

**Comment by ibilon** [comment]
@Gama11 it's far to the bottom but it's there too

**Comment by Gama11** [comment]
Hm, you're right.. I thought the libs were sorted by downloads, but it looks like that's only true for the ones at the top for some reason?

**Comment by ibilon** [comment]
Hmm it should have been and it's the case in the /all and most tags.

http://lib.haxe.org/t/game also has the issue, maybe the nulls are affecting the sorting algorithm.

**Comment by Gama11** [comment]
Want me to open a separate issue for this? This got a bit off-topic.

**Comment by ibilon** [comment]
@Gama11 please do
