### ISSUE TITLE
--skip-dependencies option in haxelib

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/haxelib#343]
When installing an extension with a dependency like `"openfl": ""`, haxelib starts downloading the latest version ( e.g. `4.0.3` ) although openfl is already present on the system ( `3.6.1` )

Now there would be two/three ways to go about this : 
- when no version number is specified, and the library exists already, use the existing library. But the drawback is that it's usually actually nice to have the latest libraries installed. So I'd rather advocate for keeping this behavior
- allow an option like `--skip-dependencies` that lets the user install dependencies on their own if they wish to
- allow an option like `--no-update` which only checks for dependencies being met, and doesn't auto-update to latest, unless dependency demands it ( `>=4` )

Having written the last paragraph actually just noticed that dependencies can't specify a version number equal to, or above. That would be a good enhancement too

**Comment by hughsando** [comment]
Yes, I would like --skip-dependencies so I can install flixel to use with NME, without 100M of lime+openfl which I do not need.
Possibly some kind of "prompt" option that allows Y/N per dependency.

**Comment by Gama11** [comment]
Sorry about that, we decided to avoid using haxelib dependencies for that exact reason for a while... But now it's become necessary to lock flixel to specific OpenFL / Lime versions.

I don't think there should be a prompt by default, that would break all sorts of CI scripts.

**Comment by hughsando** [comment]
Agree, something like --skip-dependencies  and --prompt-dependencies  or maybe
--dependencies skip
--dependencies prompt
--dependencies ifmissing

**Comment by mastef** [comment]
For starters I guess it would be just checking if the `--skip-dependencies` parameter exists in the start of this method? [src/haxelib/client/Main.hx#L960-L984](https://github.com/HaxeFoundation/haxelib/blob/development/src/haxelib/client/Main.hx#L960-L984)
