### ISSUE TITLE
classPaths in haxelib json

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/haxelib#35]
Hi

This new release of haxelib has made me give another try on it. Thanks for your work.

One thing I find annoying in dealing with haxelib is that haxelib.json need to be in the source folder along side package folder and source files.

This does not look very nice on a git repo for example where you want people to use "haxelib git ..." to grab your library.

Also if you want to have other files distributed (readme, license...) with your library they have to be put with the sources.

Could the json format allow a "classPaths" fields like this

"classPaths":["src","src2"]

most of the time only one source folder would be necessary but maybe there are some use case for multiple source folders (not any in my mind as of now but better safe than sorry.)

What do you think?

**Comment by fzzr-** [comment]
Also need to add it to [manual](http://haxe.org/manual/haxelib-json.html).
