### ISSUE TITLE
"haxelib install task" fails with Eof

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxelib#358]
Flixels Travis currently always fails during `haxelib install task`. Before that, it installs a number of other haxelibs successfully though: https://travis-ci.org/HaxeFlixel/flixel/jobs/175361450#L766

I can also reproduce this locally:

```
> haxelib install task
Downloading task-1,0,7.zip...
Download complete : 0 bytes in 0.1s (0KB/s)
Error: Eof
```

**Comment by ibilon** [comment]
Trying to access a file from the website gives the same error `Eof`.
`Failed to get file information for task/haxedoc.xml in task (1.0.7)`

Looks like the file is there but empty.
But last release is from 2015-11-01 and even has 8696 downloads.

So strange.

**Comment by andyli** [comment]
Somehow the issue is gone after I restarted the server. [bgm: x files theme song]
