### ISSUE TITLE
haxe 3.4.0-rc.1

### ISSUE THREAD

**Issue by francescoagati** [HaxeFoundation/haxelib#362]
hi,
 with haxe 3.4.0-rc.1 in config i get this error when call haxelib from folder bin inside node_modules/haxe/bin:

cannot access non-static filed toValidatable from static method

**Comment by ibilon** [comment]
I don't think that's a haxelib issue,
haxelib is compiled to a neko executable and can't fail like that when called.

I guess that's an issue for https://github.com/HaxeFoundation/npm-haxe?

**Comment by francescoagati** [comment]
ops sorry
