### ISSUE TITLE
I'm getting "Error: Http Error #502" when trying to install a lib using haxelib

### ISSUE THREAD

**Issue by b005t3r** [HaxeFoundation/haxelib#369]
The lib is not installed as an effect. Does your server need restarting maybe?

**Comment by b005t3r** [comment]
Yep, it looks like http://lib.haxe.org/ isn't working as well.

@andyli could you restart it (I think you did that the last time someone had a similar issue)

**Comment by oknoorap** [comment]
same problem here 😢

**Comment by sbimikesmullin** [comment]
same problem here

**Comment by cxsquared** [comment]
Seems to back up and working now.

**Comment by andyli** [comment]
Just woke up, noticed the issue, restarted server and it's up again. Sorry for the trouble.

At this moment, I've no idea what's wrong. But I've just gave Amazon access to @ncannasse and @waneck so when there is problem and I were not here again they can help.

Going to setup a auto server restart when the service is down. Currently we only have a auto server restart every 12 hour.

**Comment by MatthewUber** [comment]
Hi, I'm still getting the Http Error #502.

**Comment by MatthewUber** [comment]
Working now :+1:

**Comment by shintiger** [comment]
Wait for next auto restart is the only way if I face this error?

**Comment by andyli** [comment]
It's my bad. The website was down and I broke it further during fixing it.
Trying to actually fix it right now.

Andy

**Comment by andyli** [comment]
Manually deployed a new version. It's up again. (You may experience some delay due to DNS, caching etc.)

**Comment by shintiger** [comment]
Big thanks anyway

**Comment by sbimikesmullin** [comment]
haxelib is down

**Comment by andyli** [comment]
It's up again, probably "fixed" by the periodic restart.

**Comment by sbimikesmullin** [comment]
disposable architecture ftw

**Comment by jeking3** [comment]
Status?  Still down.

**Comment by andyli** [comment]
This time a mere restart didn't fix the issue, but a instance rebuild is needed. It is up again now.

Looking at the log, surprisingly, the issue was caused by a periodic restart - it went 502 just after the periodic restart. I'm so confused.

**Comment by jeking3** [comment]
Looks like it's broken again.  Getting error 503 now.

**Comment by andyli** [comment]
I was changing some config and it should be up now. Interesting that you noticed it since it was down only for few minutes... :)

**Comment by jeking3** [comment]
Haxe is a language supported by Apache Thrift, and I'm working on docker build images, so I'm hitting the server a lot right now.

**Comment by markknol** [comment]
I think this issue is resolved. If haxelib is down again, feel free to let us know again.

**Comment by sbuller** [comment]
I'm getting Http 503s today from a `haxelib install openfl`, and I see nothing at lib.haxe.org.

**Comment by sbuller** [comment]
I see two A records for lib.haxe.org, and neither IP responds to pings.

**Comment by sbuller** [comment]
Seems to be back up now

**Comment by thomasjwebb** [comment]
I periodically get `Error: Http Error #503` when trying to install stuff using haxelib (unless I directly specify a github repo) then it goes away. Right now it's happening to me again. I guess it'll probably go away soon but it would be good if there was a more permanent solution.

**Comment by Gama11** [comment]
Haxelib is indeed down right now, see also https://github.com/HaxeFoundation/haxe/issues/7037.
