### ISSUE TITLE
Type not found: HxOverrides after installing Haxe 3.4.0 (js target)

### ISSUE THREAD

**Issue by bikasx** [HaxeFoundation/haxelib#374]
1. Installed Haxe 3.4.0 (although when i enter: haxelib version it displays 3.3.0 for some reason)
2. Tried to compile to js.
3. Got this error:
C:\HaxeToolkit\haxe\std/js/_std/Array.hx:45: characters 25-36 : Type not found : HxOverrides

**Comment by bikasx** [comment]
After re-installing it somehow fixed itself... :)

**Comment by Gama11** [comment]
Are you using FlashDevelop / HaxeDevelop? Might have been an instance of https://github.com/fdorg/flashdevelop/issues/1403.

**Comment by bikasx** [comment]
Yes i do, i use HaxeDevelop. Everything else works fine though.
