### ISSUE TITLE
Run script fails on relative dev path

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxelib#379]
https://github.com/HaxeFoundation/haxelib/blob/eeac8f4e77b23b120f27d27502f43589db26d143/src/haxelib/client/Main.hx#L1445-L1458

The problem here is that if the dev path is relative, cwd will be set correctly but then it tries to use a relative path to find the executable.

So converting the path to absolute should work:
`var vdir = dev != null ? FileSystem.absolutePath(dev) : pdir + Data.safe(version);`

**Comment by noobpurple** [comment]
Yeah, I'm having the same problem here. For Arch Linux, the website recommends using ~/haxelib, which means that nothing works.

**Comment by RealyUniqueName** [comment]
This should work now.

`haxelib dev lib relative_path` transforms `relateive_path` into an absolute one: 
https://github.com/HaxeFoundation/haxelib/blob/c5afca81c7d8450007bafaf4248af1efaabf05c4/src/haxelib/client/Main.hx#L1535-L1539

`~` is handled explicitly on `haxelib setup`:
https://github.com/HaxeFoundation/haxelib/blob/c5afca81c7d8450007bafaf4248af1efaabf05c4/src/haxelib/client/Main.hx#L1214-L1221

Feel free to reopen if something related is still broken.
