### ISSUE TITLE
haxelib run (interp) with -cp args

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxelib#387]
This concerns the interp version of `haxelib run`, i.e. with a "main" entry in haxelib.json

Simply print the args for inspection:
```haxe
class Main {
  static function main()
    trace(Sys.args());
}
```

`haxelib run lib_name arg1` gives `['arg1', '<cwd>']`, which is correct
`haxelib run lib_name -cp arg1` gives `['-cp', '<lib_path>/arg1', '<cwd>']`, which is wrong

Note how the argument after `-cp` is prepended with the `<lib_path>`
What make it worse is that if the folder `<lib_path>/arg1` doesn't exists, it fails.

This doesn't happen with the neko (`run.n`) version

**Comment by RealyUniqueName** [comment]
I cannot reproduce this with haxelib bundled in the latest dev Haxe.
Could you please check if it still happens for you?
