### ISSUE TITLE
haxelib --quiet install

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxelib#389]
I'm using haxelib in travis https://github.com/jtransc/jtransc/pull/236#issuecomment-321368128

But the progress of the Downloading part occupies like 80% of the whole log, and travis takes a lot of time to load because of that.
Can you make the --quiet to not display progress? Or display it less frequently? Or add another option to no display anything at all?

**Comment by Gama11** [comment]
IIRC, we had to redirect to `/dev/null` so that logs wouldn't get too big...

https://github.com/HaxeFlixel/flixel/blob/4.3.0/.travis.yml#L27-L41

**Comment by soywiz** [comment]
Yep. We ended doing the same, thanks!. But that also disables other potentially relevant output.
Also it seems that the buffer/split is something like 1K so 40MB are 40.000 lines of output. Growing that or limiting line outputs to something like 10 times per second, and honoring --quit would be better I think.

**Comment by sebthom** [comment]
@andyli Wouldn't that be solved by https://github.com/HaxeFoundation/haxelib/pull/373 ?

**Comment by andyli** [comment]
Yeah, I think #373 is in the right direction. Not sure if there is any other places that should respect `--quiet`, but I will just merge that first.

**Comment by RealyUniqueName** [comment]
Duplicates #371
