### ISSUE TITLE
stable haxelib does not detect run scripts on macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by algorev** [HaxeFoundation/haxelib#395]
With the haxelib (3.3.0) bundled with haxe (3.4.3) in the official download from the website, The installs work perfectly, but the haxelib run commands don't work on any package. Whatever the package, the message is the same:
`$ haxelib setup haxe`
`haxelib repository is now haxe`
`$ haxelib install lime`
`Downloading lime-5,6,0.zip...`
`Download complete : 88088944 bytes in 17.7s (4853.6KB/s)`
`Installing lime...`
`  Current version is now 5.6.0`
`Done`
`$ haxelib run lime setup`
`Error: Library lime version 5.6.0 does not have a run script`
`$`
Tested with lime, openfl and kha.

**Comment by andyli** [comment]
What OS?

**Comment by andyli** [comment]
Ah, didn't notice you mentioned macOS Sierra 10.12.6 in the title. But I've just checked and it ran fine on my Mac (also 10.12.6).

Do you happen to have run `haxelib selfupdate` before? You can tell from having `haxelib_client` or `haxelib` in `haxelib list`. If so, try remove them (you may simply manually delete the `path/to/haxelib_repo/haxelib/` and `path/to/haxelib_repo/haxelib_client/` folders).

**Comment by algorev** [comment]
I didn't self-update. I deleted the repo numerous times and now the only
package showing up in the list is "lime", which, as mentioned above, cannot
be ran.

**Comment by algorev** [comment]
My bad. It seems to have been a environment variable refresh problem. Should close this! (or warn for dumb people like me)

**Comment by andyli** [comment]
Glad to hear you solved it :)
