### ISSUE TITLE
Last installed library is not active.

### ISSUE THREAD

**Issue by alexey-kolonitsky** [HaxeFoundation/haxelib#396]
If first I install last version of library and then install specific version of this library, The last version still used. 

```
>haxelib install actuate
>haxelib list
actuate: [1.8.7]
```

```
>haxelib install actuate 1.8.1
>haxelib list
actuate: 1.8.1 [1.8.7]
```

**Comment by Simn** [comment]
That looks fine to me, the fact that you install it doesn't necessarily imply that you want to set it as the default version. It's better to be explicit about that by using `haxelib set`.

**Comment by ibilon** [comment]
It could ask if you want to set it, like it does when you update.

**Comment by Simn** [comment]
I hate when my CLI talks back to me and wants my attention. :( That always causes problems in scripts...

**Comment by ibilon** [comment]
Yes that's annoying, but with the correct options available (-y, -n, -a) it's less of an issue I think.
Personally I hate when cli tells me to do something instead of proposing to do it for me (I look at you haxe "lib foo not installed do haxelib install foo")

**Comment by alexey-kolonitsky** [comment]
I'm ok to use `haxelib set` after `install` but it should be clear. If behaviour is ok, it should be mentioned in documentation. The second option is print some warning message about using `haxelib set` after `install` if installed version less then current.
