### ISSUE TITLE
Getting run.n file

### ISSUE THREAD

**Issue by pawel-miczka** [HaxeFoundation/haxelib#397]
Hi,

I'm writting console application in haxe. I read that i need run.n script in my directory. Where I can find one or how to generate it? Also do you have any tutorials where I could learn how to write "professional" command application?

**Comment by back2dos** [comment]
You will have to compile to neko with `-neko run.n`. Alternatively you can specify a [`main`](https://github.com/HaxeFoundation/haxelib/blob/development/src/haxelib/Data.hx#L153) class in your haxelib.json, in which case `haxelib run yourLib` is practically equivalent to `haxe -lib yourLib --run SpecifiedMainClass`.

As for the rest, I wouldn't know. My advise would be to look at a command line tool you like, read its sources and emulate its behavior ;)

**Comment by pawel-miczka** [comment]
I found this package: https://github.com/andywhite37/hmm but It has compiled run.n file and I just want to know how to make this one or how to properly setup runnable haxelib.

**Comment by back2dos** [comment]
I'm not sure which part was unclear. The `run.n` in hmm is compiled exactly as I said: https://github.com/andywhite37/hmm/blob/master/build.hxml#L7

Alternatively on could simply put `"main": "hmm.Hmm"` into the `haxelib.json` and not to prebuild the neko file. The benefit benefit is that it'll work also in environments where neko is not easy to install (some Linux distros or OSX versions exhibit this problem).

**Comment by pawel-miczka** [comment]
Aw ... got it. I thought It is compiled in other way. Thanks :)

**Comment by markknol** [comment]
I think this is resolved. If there are more questions, let us know!
