### ISSUE TITLE
Haxelib website introduction missed

### ISSUE THREAD

**Issue by alexey-kolonitsky** [HaxeFoundation/haxelib#402]
![2017-12-27_7-07-32](https://user-images.githubusercontent.com/401912/34371371-3f9a1b0c-ead5-11e7-9d47-e5b684babdb2.png)

**Comment by alexey-kolonitsky** [comment]
The same issue with manual item from "Learn Haxe" menu

**Comment by nadako** [comment]
@markknol is this something you could handle?

**Comment by markknol** [comment]
Yes will look at it soon

**Comment by markknol** [comment]
This is fixed
