### ISSUE TITLE
Dependency fails silently with malformed json

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxelib#406]
(copied from https://github.com/HaxeFoundation/haxe/issues/6829)

```json
"dependencies":
  {
    "hexinject": "git:https://github.com/DoclerLabs/hexInject.git",
  }
```
Because of the comma addition, the application will be compiled without the haxelib dependency.
On a big project, believe me, it takes time to catch this error. I would expect to get an error message, or at least a warning somewhere.

**Comment by markknol** [comment]
(..or use a more tolerant JSON parser 👍)
