### ISSUE TITLE
`haxelib libpath` to return root path of a library

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/haxelib#407]
~Currently it seems that `haxelib path` returns a lot of unformatted extra-information, instead of just the path. It would be great if the extra information was hidden behind a flag, or a flag could be provided that would only return the path of the library - as the command suggests.~

`haxelib path` returns the paths of libraries' source files + compiler flags. It would be great to have a command where just the `root path` of a library would be returned.

This way `haxelib libpath` can be used to programmatically work with library locations - e.g. to detect current [git commit of libraries in use at build time](https://code.haxe.org/category/macros/add-git-commit-hash-in-build.html), etc.

Desired output : 
```bash
$ haxelib libpath openfl-samples
/usr/local/lib/haxe/lib/openfl-samples/4,0,0/
```

```bash
$ haxelib libpath openfl
/somewhere/unexpected/openfl/
```

```bash
$ haxelib libpath tink_macro
/usr/local/lib/haxe/lib/tink_macro/0,15,4/
```

**Comment by back2dos** [comment]
Hmm, maybe the command documentation should be improved, but that's really not what it's for. It's primarily intended for the Haxe compiler to get all the necessary arguments for a library (classpath, defines, macros etc.) and its dependencies.

**Comment by Gama11** [comment]
It's frequently used the way @mastef describes though... There's code to parse the path out of `haxelib path` output in flixel as well as flixel-tools, for instance.

**Comment by mastef** [comment]
Same in lime - there's a whole helper to try and scan the lines for haxelib.json files, to see if they're parse-able, then to compare if the library name in them matches the one it's looking for etc. It seems overkill. I've submitted a PR now with a `pathonly` option

**Comment by elsassph** [comment]
`haxelib path` is doing a specific job, returning *classpaths* and extra compiler arguments - you want another feature.

Do you need the folder of the haxelib? Or the classpath of the haxelib? (it can be a subfolder)

**Comment by mastef** [comment]
Yep @elsassph @back2dos I've adjusted the issue and the PR.
