### ISSUE TITLE
Reset password?

### ISSUE THREAD

**Issue by apemanzilla** [HaxeFoundation/haxelib#415]
I'm having issues logging in to submit a package, is there a way to reset my password?

**Comment by markknol** [comment]
@andyli

**Comment by andyli** [comment]
Send me an email (address can be found on my profile) with the md5 hash of your new password. Make sure the password you choose is not used by any of your other accounts because I can tell you the haxelib server is quite poorly secured...

**Comment by andyli** [comment]
done
