### ISSUE TITLE
No way to transfer ownership of a library

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxelib#418]
I am the original author [haxe-continuation](https://github.com/haxe-continuation/haxe-continuation), I want to transfer the ownership of https://lib.haxe.org/p/continuation to @AxGord .

If it is not possible in the cli program,  @Simn could you please modify the database of https://lib.haxe.org/ for the transfer?

**Comment by markknol** [comment]
Afaik, You can append the new maintainer user name in haxelib.json and release that as new version. After that the new maintainer can release under his account.

**Comment by Atry** [comment]
Thank you!

**Comment by Atry** [comment]
@AxGord Could you please register a user in `haxelib`, so I can append you as an owner?

**Comment by AxGord** [comment]
@Atry Yes, my user in haxelib: https://lib.haxe.org/u/AxGord/
