### ISSUE TITLE
README/LICENSE sometimes don't work

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxelib#419]
Calling for some help for the updated haxelib website. 

Some observations:

* http://staging-lib.haxe.org/p/flixel/ readme does show, good
* http://staging-lib.haxe.org/p/flixel/ license/changelog doesn't show, while it has both as markdown in the zip (in root)
* http://staging-lib.haxe.org/p/openfl/ readme/changelog/license doesn't show, while the zip does contains them (in openfl/*.md)
* http://staging-lib.haxe.org/p/openfl/8.0.2/files/ does give an error  `Failed to get file information for in openfl (8.0.2) [file_open,/var/www/html/files/3.0/openfl-8,0,2.zip]`

On my local machine (with some limited dummy data and downloaded zips) it does work and cannot really reproduce the issue.

This is the source code for getting the readme/license files:
https://github.com/HaxeFoundation/haxelib/blob/development/src/website/controller/ProjectController.hx#L237-L240
I wanted to support multiple extensions and from some common directories, that's why its bit more code than before. 

This is the template part:
https://github.com/HaxeFoundation/haxelib/blob/development/www/view/project/version.html#L30

Now, I _think_ the code is correct, but I think there is some weird caching mechanism going on regarding getting files from the zip. I have _the feeling_ that once it decided it cannot access a file, it will never work from that point.

Who wants to help me?
@simn @ibilon @jasononeil @andyli

**Comment by ibilon** [comment]
The problem we had in https://github.com/HaxeFoundation/haxelib/issues/281 is that the admin tool to clear the cache wasn't working.
And ufront + dependency injection makes it hard to debug, and hard to find someone who can debug it.

**Comment by andyli** [comment]
Also fixed by e4a5e57.
I still haven't look into how caching works yet, but seems to work without adjusting anything...
