### ISSUE TITLE
New haxelib site TODOs

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxelib#420]
* [x] home: move "Many libraries are just one .. " down
* [x] home: less popular libs
* [x] readme: fix regression. on staging the readme images are broken, while on http://lib.haxe.org/p/flixel/ they're not
* [x] recent updates: has null authors
* [ ] https://github.com/HaxeFoundation/haxelib/issues/419 README/LICENSE sometimes don't work

After this, new site is ready to go live

**Comment by andyli** [comment]
We should sync dev/master soonish. If there is still problems with the new layout, I would recommend move it to another branch and then reset development to master.

**Comment by markknol** [comment]
Sorry, atm I don't have much time to work on it unfortunately. 
I did removed the author from recent list.

Will try to make it deployable this week, otherwise indeed lets move it to a branch.

**Comment by markknol** [comment]
I did some updates, list is now almost complete. 

The only thing left is that weird caching thing that makes the READMEs sometimes not work. I'd love to see that fixed but we need a smart person to fix that. 

Currently Travis fails because of something. If that works again, lets do a final check on staging and maybe then update is good to go (?)
cc @Gama11 @Simn

**Comment by andyli** [comment]
Thanks, Mark. I've just fixed CI and site is on https://staging-lib.haxe.org/ now.

**Comment by markknol** [comment]
Its pushed to live, so this can be closed
