### ISSUE TITLE
[URGENT] Can't submit to haxelib

### ISSUE THREAD

**Issue by RaidAndFade** [HaxeFoundation/haxelib#423]
http://lib.haxe.org/index.n automatically 302s to https but haxelib relies on http and thus fails to upload the temporary file, leading to the submit action failing.

I've successfully submitted using https urls with postman so a seemingly easy fix is just to change http urls to https. (specifically the one that uploads the zip file)

**Comment by andyli** [comment]
Fixed in c8014ca59ba0ecc7603a2a69ba08d966ebb5167b by disabling redirect for requests to index.n.

Actual support for using https in the haxelib client still need some work.
