### ISSUE TITLE
Cannot submit a package

### ISSUE THREAD

**Issue by endel** [HaxeFoundation/haxelib#424]
Hi there,

I'm trying to submit my first haxelib, and unfortunately I'm getting this error:

```
$ haxelib submit fossil-delta.zip
This is your first submission as 'Endel Dreyer'
Please enter the following information for registration
Email : endel.dreyer@gmail.com
Fullname : Endel Dreyer
Password :
Confirm :
Error: Invalid user name, please use alphanumeric characters
```

I've created an account a while back, and I'm not sure if this can be a password issue? 
My user name is: https://lib.haxe.org/u/endel

Any help is appreciated. Cheers

**Comment by endel** [comment]
My package is super small btw: only 7kb

**Comment by andyli** [comment]
Looks like you've put "Endel Dreyer" in the haxelib.json "name" field, which should be the username, but not fullname. Try change it to your username "endel".

**Comment by endel** [comment]
@andyli oops, that's right! Thanks a lot. It works!
