### ISSUE TITLE
How to test haxelib?

### ISSUE THREAD

**Issue by pawel-miczka** [HaxeFoundation/haxelib#428]
Hi, I have a problem.

I created small haxelib on my local computer which is inside D:\Projekty\mtasa-haxe-types (code is here: https://github.com/pawel-miczka/mtasa-haxe-types) and I'm trying to test it. To do this I use 

```
haxelib dev mtasa-haxe-types D:\Projekty\mtasa-haxe-types
```

and in another project I can't use 

```hx
import mtasa.server.Core;
```

Why? What I'm doing wrong?

**Comment by EricBishton** [comment]
Are you adding `-lib mtasa-haxe-types` to your `haxe` command line (or including that library in your .hxml, or other project file)?

**Comment by pawel-miczka** [comment]
Good question, I don't :D. I will test it later today. I will write respond.

**Comment by pawel-miczka** [comment]
Working fine, thanks :)
