### ISSUE TITLE
Haxelib from Homebrew on macOS High Sierra 10.13.6: "Could not link to neko"

### ISSUE THREAD

**Issue by algorev** [HaxeFoundation/haxelib#429]
On my machine (Haxe 3.4.7 and Haxelib 3.3.0 from Homebrew on macOS High Sierra, Neko 2.2.0 from Homebrew too), Haxelib prefixes the output of every `haxelib run` command with the text:

`Could not link to neko.`

I have also observed that it makes it impossible to build projects with OpenFL, as build commands:

`$ haxelib run openfl build macos`

give the following output:

`Could not link to neko.`

`Warning: Ignoring requested haxelib "openfl" version "3.6.1" (version "8.4.1" was already included)`

`Could not link plugin to process (CFFILoader.h 203) - with neko`

**Comment by tobil4sk** [comment]
This error is not related to `haxelib run`, it happens when `lime.ndll` tries to load `libneko.dylib`. Similar issue here: https://github.com/openfl/lime/issues/1750
