### ISSUE TITLE
Type not found : haxe.remoting.Connection

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [HaxeFoundation/haxelib#430]
I tried building haxe and it also builds haxelib which it includes as submodule, but when I call `make` it builds and then fails in the end with

```sh
(cd /Users/Leonidas-from-XIV/haxe/extra/haxelib_src && /Users/Leonidas-from-XIV/haxe/haxe client.hxml && nekotools boot run.n)
Type not found : haxe.remoting.Connection
```

According to the changelog it was moved to `hx3compat`, but the `client.hxml` mentions `-cp hx3compat/std`.

**Comment by Simn** [comment]
haxelib has hx3compat as a submodule, so you have to clone with `--recursive` or do `git submodule init && git submodule update`.

**Comment by DQvsRA** [comment]
People please pay more attention to developer tools, not to complicate the language, which nobody can use.
```
$ haxe -version
4.1.1
$ haxelib install openfl
Type not found : haxe.remoting.Connection
```
