### ISSUE TITLE
[Website] Files not for currently selected version

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxelib#433]
When clicking on "Files" tab on not latest version, for instance here:
https://lib.haxe.org/p/hlsdl/1.7.0/

This will link to latest version instead, for instance:
https://lib.haxe.org/p/hlsdl/1.8.0/files/
Instead of
https://lib.haxe.org/p/hlsdl/1.7.0/files/

Side thing : a diff between versions would be cool :)

**Comment by gogoprog** [comment]
I'm also interested in this

**Comment by tobil4sk** [comment]
Fixed in #524
