### ISSUE TITLE
haxelib of Haxe4-win64 not working with Neko-win64

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxelib#435]
When trying to execute `haxlib` of Haxe 4.preview5 (**64**bit) with Neko 2.2.0 (**64**bit) on PATH I get the following error:

![haxelib](https://user-images.githubusercontent.com/426959/48984091-8e500f80-f0f7-11e8-96da-8dd29aa29aab.png)

It only seems to works if I use the 32bit version of Neko.

**Comment by andyli** [comment]
haxelib bundled from the haxe win 64-bit archive is indeed 32-bit. One reason is that Neko only provides JIT for Windows 32-bit, so the 32-bit version is quite faster then the 64-bit version.
So, always use 32-bit Neko on Windows, even if you're using 64-bit Haxe. Alternatively, rebuild haxelib yourself.

**Comment by sebthom** [comment]
@andyli Thanks for the prompt explanation! I opened this issue because I didn't find any information about this elsewhere. Do you think you could add a notice in the haxelib readme about it. or even better, would it technically be feasible for haxelib.exe to check whether neko 32 or 64 bit is used ad display a user friendly error message?

**Comment by andyli** [comment]
> add a notice in the haxelib readme about it

Sure. Would you send us a PR?

> for haxelib.exe to check whether neko 32 or 64 bit is used ad display a user friendly error message

Maybe, but I have no idea now to do that at the moment.

**Comment by ncannasse** [comment]
Maybe we should have "haxelib.bat" (+.sh) instead as a shortcut to run haxelib within eval ? (I think it should run quite well)

**Comment by andyli** [comment]
We discussed it several times, also IIRC Haxe NPM package tried it and reverted to using haxelib.exe. The main problems are:
 * Most haxelib's run scripts are `run.n`.
 * haxelib's own self-update uses `run.n` as well.
 * The eval sys api is not completed, e.g. missing https.

**Comment by RealyUniqueName** [comment]
Original issue is fixed. See https://github.com/HaxeFoundation/haxe/issues/8419 for details.
