### ISSUE TITLE
haxelib run with "main"

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxelib#446]
![image](https://user-images.githubusercontent.com/1022912/54492625-8398d080-48c8-11e9-87a2-90aba5724b0d.png)

The option to use "main" for a Run class is not documented on haxelib website, and VSCode warns against, while we would it to become the default with Haxe 4.0 

I think when a Run.hx is present we should run it directly (unless there's a run.n ofc), and still allow to configure "main"

**Comment by Gama11** [comment]
I guess somebody needs to update the `haxelib.json` schema hosted on http://schemastore.org/json/. [That's what vshaxe uses](https://github.com/vshaxe/vshaxe/blob/ca4c0aa20c7e47cce177357325dc7de923290afc/package.json#L813).

**Comment by back2dos** [comment]
> I think when a Run.hx is present we should run it directly 

Present where though? The library root? Or the classPath?

**Comment by RealyUniqueName** [comment]
PR to json schema: https://github.com/SchemaStore/schemastore/pull/817

**Comment by Gama11** [comment]
The schema is also part of this repo: https://github.com/HaxeFoundation/haxelib/blob/development/schema.json

**Comment by RealyUniqueName** [comment]
json schema was merged into schemastore
