### ISSUE TITLE
Error: ssl network error after installing haxe 4.0.0-rc.2

### ISSUE THREAD

**Issue by zhaoterryy** [HaxeFoundation/haxelib#448]
Getting ssl network error when trying to install libraries behind a proxy. Reverting to Haxe 3.4.7 works fine.

```
$> haxelib install all
Loading info about the required libraries
Error: ssl network error

Called from haxe/remoting/HttpConnection.hx line 63
Called from /Users/travis/build/HaxeFoundation/haxe/std/sys/Http.hx line 58
Called from /Users/travis/build/HaxeFoundation/haxe/std/sys/Http.hx line 245
Called from /Users/travis/build/HaxeFoundation/haxe/std/sys/Http.hx line 60
Called from haxe/remoting/HttpConnection.hx line 64
Called from haxelib/client/Main.hx line 51
Called from haxelib/client/Main.hx line 773
Called from haxelib/client/Main.hx line 656
Called from haxelib/client/Main.hx line 422
```

Thanks!

**Comment by pchertok** [comment]
Note that when you replace the haxelib.exe binary in 4.0rc2 with the one from 3.4.7 everything works fine.

**Comment by ncannasse** [comment]
@andyli something neko-related maybe ?

**Comment by andyli** [comment]
I cannot reproduce that with the haxe 4.0.0-rc.2 Windows 64-bit installer.

Here are the md5 hashes of haxelib.exe and neko.exe, just to make sure we're testing the same thing.
```
C:\Users\Andy>certUtil -hashfile C:\HaxeToolkit\haxe\haxelib.exe md5
MD5 hash of C:\HaxeToolkit\haxe\haxelib.exe:
f2e6f6e145a3fd3883f4dda9c98430b5
CertUtil: -hashfile command completed successfully.

C:\Users\Andy>certUtil -hashfile C:\HaxeToolkit\neko\neko.exe md5
MD5 hash of C:\HaxeToolkit\neko\neko.exe:
560d281a69a521fc9500c163da49d139
CertUtil: -hashfile command completed successfully.
```

**Comment by andyli** [comment]
Oh, wait, I missed the detail that you're using a proxy.
How did you config the proxy? I have never used one before.

BTW, the reason 3.4.7's haxelib.exe works most likely is because it use lib.haxe.org without https. The newer haxelib use https by default.

**Comment by pchertok** [comment]
That makes sense, in order to get npm to work we need to set strict-ssl to false.

**Comment by jimsungi** [comment]
I met same situation. I'm behind proxy server, too. Anyway, I want to test 4.0.0rc2 with CJK support, so I use trick. Install 4.0 haxelib, Use 3.0 haxelib binary when you install/update library, then back to 4.0 haxelib binary. - haxelib.exe enough -  It works fine for me.  ( It works great open-fl + flash / html5 backend with Korean, but not neko backend. While CJK support working, I think this trick works)

**Comment by ncannasse** [comment]
We should add an option to haxelib (either with command parameter or maybe better env var) to disable https (or disable SSL cert check)
