### ISSUE TITLE
haxelib git deletes its dependencies when installing the second time

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxelib#458]
This is a regression.

Steps to reproduce:

* Create a new file called `test.hxml` with the following contents:

```
-lib jwt:git:https://github.com/proletariatgames/haxe-jwt.git#8cea1b9bea43d465a0b4aeecd436be475f7b950b
```

* Run `haxelib install test.hxml`
* Set `a` when it asks you to continue
* Run `haxelib install test.hxml` again
* Set `a` when it asks you to continue
* Run `haxelib path jwt`

It will fail with the following error:
```
haxelib path jwt
Error: Library jwt version git is not installed

Called from haxelib/client/Main.hx line 1410
Called from haxelib/client/Main.hx line 1433
Called from haxelib/client/Main.hx line 470
```

**Comment by remiX-** [comment]
+1
