### ISSUE TITLE
haxelib deletes git folder

### ISSUE THREAD

**Issue by CrazyFlasher** [HaxeFoundation/haxelib#479]
Test case:
`haxelib git spritesheet https://github.com/CrazyFlasher/spritesheet.git f0b1dcec93afec6729b2c9cc108a12f9c2d9cfd8`
Creates git folder
Run again
```
haxelib git spritesheet https://github.com/CrazyFlasher/spritesheet.git f0b1dcec93afec6729b2c9cc108a12f9c2d9cfd8`
You already have spritesheet version git installed.
Overwrite branch: <unspecified> with "f0b1dcec93afec6729b2c9cc108a12f9c2d9cfd8" [y/n/a] ? y
Library spritesheet current version is now git
```
Deletes git folder
Tested with 4.0.0-rc.5, but I think same behaviour in 4.0.0 release version

**Comment by RealyUniqueName** [comment]
This was fixed in 4.0.0: #458
