### ISSUE TITLE
Cannot use private libs anymore

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxelib#484]
Since #473, compiling with my private libs leads to this error:
```
Error: Error: Cannot process [xxx]: missing field license
```
Followed by this if I set `"license": ""`:
```
Error: Error: Cannot process [xxx]: Invalid value  for License
```

I am now supposed to add one of these for a private lib in order to compile my project:
```
"GPL", "LGPL", "BSD", "Public", "MIT", "Apache"
```

**Comment by ibilon** [comment]
I think we should keep the full haxelib.json check, but add an "Other" value for license, and a check on upload to lib.haxe.org that it's not "Other".

**Comment by ncannasse** [comment]
That annoyed me too, I had to add a user name and a license for private libraries which didn't required it before.
