### ISSUE TITLE
[haxe 4.0.1] problems with private libs

### ISSUE THREAD

**Issue by Klug76** [HaxeFoundation/haxelib#487]
Haxe 4 brought new problems with private libraries. Now you need to enter a certain (inappropriate) license, so also the name of the private library should be longer than 2 characters!
Please please return support for short private names.

**Comment by ibilon** [comment]
Should have been fixed by https://github.com/HaxeFoundation/haxelib/pull/485.

**Comment by RealyUniqueName** [comment]
Fixed by #485
