### ISSUE TITLE
No option for non-open source license

### ISSUE THREAD

**Issue by hughsando** [HaxeFoundation/haxelib#488]
It is not possible to use haxelib for internal libraries without giving your code an open-source license.
At least one option should be for internal code, or it should simply not check the license at run time. (is it really needed when doing a 'haxelib path lib' ?) ie. just check on the server when uploading.
Possible extra licenses types:  private, commercial, internal, custom

**Comment by RealyUniqueName** [comment]
Try removing `license` field altogether. That should stop haxelib complaining about invalid license.

**Comment by hughsando** [comment]
`Error: Cannot process [mylib]: missing field license`

**Comment by RealyUniqueName** [comment]
That should be fixed in the latest haxelib (since 4.0.2).
What does your `$ haxelib version` say?

**Comment by hughsando** [comment]
4.0.1 - so maybe an update should do it.
