### ISSUE TITLE
"Error: Failed to call haxelib (command not found ?)" for some targets on fresh Haxe 4.0.3 Win64 install

### ISSUE THREAD

**Issue by DustinWehr** [HaxeFoundation/haxelib#489]
This is an issue with the release from https://haxe.org/download/. Not sure if it should go here or in HaxeFoundation/haxelib.

Using Main.hx from https://haxe.org/manual/target-java-getting-started.html.

These yield the error in the title of this issue:
- `haxe -main Main --java javaout` I did install hxjava.
- `haxe -main Main --cs csout`

These run without errors:
- `haxe -main Main --cpp cppout`
- `haxe -main Main --python pyout.py`
- `haxe -main Main --js jsout.js`
- `haxe -main Main --neko nekoout`
- `haxe -main Main --interp`

I haven't tried any of the other targets.

**Comment by RealyUniqueName** [comment]
Did you run the installer or just unpacked compiler binaries?
What happens if you run `haxelib` in cmd?

**Comment by DustinWehr** [comment]
Happens both with the installer and the unpacked binaries.
I get nothing when I run `haxelib` in PowerShell. No error - just a new prompt. 
I hadn't tried cmd. When I run `haxelib` in there, I get a dialog box titled "haxelib.exe - System Error" with the text "The code execution cannot proceed because neko.dll was not found. Reinstalling the program may fix this problem."

I will try as it suggested.

**Comment by DustinWehr** [comment]
Reinstalling fixed it. I admit that I did not follow the recommendation to close all open programs when I installed the first time. I can't remember a time when that actually bit me.

**Comment by RealyUniqueName** [comment]
That's unlikely to cause the failure. I guess something broke neko installation. Or maybe you accidently unticket the neko box during installation.
