### ISSUE TITLE
Doesn't work haxelib git from Azure Repos

### ISSUE THREAD

**Issue by kurono-yuzuru** [HaxeFoundation/haxelib#491]
[environment]
windows 10
git version 2.25.0.windows.1
haxe 4.0.5
Haxe Library Manager 4.0.2

The following command did not work.
> haxelib git [project-name] [azure-repos-clone-url(HTTPS)*1]
> haxelib git [project-name] [azure-repos-clone-url(SSH)*1]

*1: The target Azure Repos is private repository

message:
> Installing [project-name] from [azure-repos-clone-url]
	Error: Could not clone Git repository.

**Comment by Aurel300** [comment]
How would you normally clone the repo? Over SSH, is the command `git clone git@<something>.git`?

**Comment by kurono-yuzuru** [comment]
Clone with the following command

> git clone [Organization]@vs-ssh.visualstudio.com:v3/[Organization]/[project]/[repository]

**Comment by RealyUniqueName** [comment]
`haxelib git [project-name] [azure-repos-clone-url(HTTPS)*1]` just runs `git clone --recursive [azure-repos-clone-url(HTTPS)*1]` under the hood.
Check if that works outside of `haxelib git` and make sure to provide correct `[azure-repos-clone-url(HTTPS)*1]`

**Comment by kurono-yuzuru** [comment]
As a result of executing git clone --recursive, an error occurred because the target repository set a submodule and the URL of the submodule was incorrect.

After fixing the submodule url, I ran the haxelib git command and it worked fine.

Thanks a lot.
