### ISSUE TITLE
Create global command

### ISSUE THREAD

**Issue by pawel-miczka** [HaxeFoundation/haxelib#492]
Hi,

I want to create global command like it is possible in nodejs. Is there some lib or tutorial how to create one?

**Comment by RealyUniqueName** [comment]
I don't think so.
But OpenFL does that if you run `haxelib run openfl setup` IIRC. Try looking into their runscripts.

**Comment by Gama11** [comment]
Libraries like Lime / OpenFL / Flixel usually just copy a file next to `haxe.exe`, which can reasonably be assumed to be in the `PATH`. That does seem rather messy though, it would be nice if there was a proper mechanism for this.

**Comment by pawel-miczka** [comment]
Ok thanks for answers :)
