### ISSUE TITLE
Embed resource in a haxelib package

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/haxelib#494]
I'm making a package that needs to be compiled with some text files embedded into it. Projects that depend on my package, shouldn't need to worry about those text files in any way.

I see that you can compile resources in with the `--resource` compiler flag, and that you can specify compiler flags for a haxelib package by providing `extraParams.hxml`. I thought I could combine those two features to do what I need, like so:

extraParams.hxml in my package:
```
--resource src/hiss/stdlib.hiss
--resource test/std.hiss
```

It looks like instead of what I want, those params are getting appended to the compiler call for the dependent project, so the DEPENDENT project looks in those relative paths to find and compile in the text files. And it can't find them.

Is there another approach to this I should be using?

**Comment by RealyUniqueName** [comment]
I think you have to use macros to embed resources from a haxelib.
It's possible to resolve a path to the current hx file in macros: https://github.com/RealyUniqueName/Coro/blob/master/src/hx/Coro.hx#L38-L39

**Comment by NQNStudios** [comment]
Ok, I implemented a macro file-loading system for a previous project and was hoping the `--resource` feature would make that obsolete. I can bring it back to fix my problem, but I do think something as convenient as `--resource` for a haxelib package could be a worthwhile use-case to support.

**Comment by NQNStudios** [comment]
Whatever this was for, I can't remember, and I don't need the feature anymore.
