### ISSUE TITLE
Register: does not correctly support accented characters for the full name?

### ISSUE THREAD

**Issue by cedx** [HaxeFoundation/haxelib#497]
I've just registered the account `cedx` with the following full name:
`Cédric Belin`

The registration seemed to be OK, but when I'm reading my account information, the full name was truncated to the first character only:

```shell
$ haxelib user cedx
Id: cedx
Name: C
```

Also: https://lib.haxe.org/u/cedx/

As issue #91 is still not fixed, can someone update my full name to `Cédric Belin` for me?

Haxe: v4.0.5 (Windows 64-bit)
Haxelib: v4.0.2

**Comment by andyli** [comment]
I've just updated the db as requested, but I think Neko, which is used as haxelib client and server, doesn't handle haxelib user name as utf8 properly.

![Screenshot_2020-05-03 cedx (C�dric Belin) on Haxelib](https://user-images.githubusercontent.com/103977/80908888-3ab70c00-8d56-11ea-9a97-4f2480dedf66.png)

Do you want me to change it to a `e` or something?

**Comment by cedx** [comment]
Thanks @andyli . Yes, it would be better to remove the accent, and set my full name to `Cedric Belin`.

**Comment by andyli** [comment]
Done :)

**Comment by cedx** [comment]
Thanks a lot @andyli !
