### ISSUE TITLE
Would like to delete other copies of my repo from haxelib

### ISSUE THREAD

**Issue by Tanz0rz** [HaxeFoundation/haxelib#501]
I have been going back and forth with the name for my library during development. I would like to delete the two versions of it that have an outdated name. The name I have settled on is the non-hyphenated `haxefmod`. 

The two versions that I want deleted (the few downloads on them are from me):

- [faxe2](https://lib.haxe.org/p/faxe2/)
- The hyphenated version [haxe-fmod](https://lib.haxe.org/p/haxe-fmod/)

**Comment by RealyUniqueName** [comment]
@andyli ^

**Comment by andyli** [comment]
done

**Comment by Tanz0rz** [comment]
Ty!
