### ISSUE TITLE
Support "long paths" on Windows

### ISSUE THREAD

**Issue by rb1147x** [HaxeFoundation/haxelib#506]
I ran into this problem while using `haxelib dev`:

```
haxelib dev better-sqlite3 C:\Program Files\Haxe Toolkit\haxe\lib\better-sqlite3\0,0,1
Directory C:\Program does not exist
```

As I googled the problem, I found several pages and threads suggesting to add `"`'s like `"C:\Program Files\Haxe Toolkit\haxe\lib\better-sqlite3\0,0,1"`, `""C:\Program Files\Haxe Toolkit\haxe\lib\better-sqlite3\0,0,1""`, `C:\"Program Files"\"Haxe Toolkit"\haxe\lib\better-sqlite3\0,0,1`, etc, but none of those worked.

However, using the short path version works:

```
haxelib dev better-sqlite3 C:\PROGRA~1\HAXETO~1\haxe\lib\BETTER~1\0_0_1~1
Development directory set to C:\PROGRA~1\HAXETO~1\haxe\lib\BETTER~1\0_0_1~1
```

I'm assuming this is due to Windows "long paths" not being supported.

While I encountered this using haxelib, I'm wondering if it's a problem in the way Haxe (or just Neko?) deals with paths on Windows?

Thanks.

**Comment by Aurel300** [comment]
No, the error is very clearly indicating that the problem is with the spaces. Without quotes, `C:\Program` and `Files\...` look like two (or more) separate arguments. Long paths should not be a problem, we don't rely on ancient libraries to do this. I think your first alternative, with a single pair of double quotes should work. Maybe try to use forward slashes, or double the backslashes? So `haxelib dev better-sqlite3 "C:\\Program Files\\Haxe Toolkit\\..."`

**Comment by rb1147x** [comment]
Fascinating, both of your suggestions work, thanks!:

```
haxelib dev better-sqlite3 "C:\\Program Files\\Haxe Toolkit\\haxe\\lib\\better-sqlite3\\0,0,1"
Development directory set to C:\Program Files\Haxe Toolkit\haxe\lib\better-sqlite3\0,0,1
```

```
haxelib dev better-sqlite3 "C:/Program Files/Haxe Toolkit/haxe/lib/better-sqlite3/0,0,1"
Development directory set to C:\Program Files\Haxe Toolkit\haxe\lib\better-sqlite3\0,0,1
```

and then they both show the dev path as:

```
haxelib list
better-sqlite3: [dev:C:\Program Files\Haxe Toolkit\haxe\lib\better-sqlite3\0,0,1]
```

Although adding in additional slash is inconvenient from a quick copy + paste, it's still much quicker than getting the short path.

I'm curious why a single backslash doesn't work. That's how folders paths are presented in the file explorer. Is this something that haxelib could support in the future?

**Comment by RealyUniqueName** [comment]
No. Single backslash in a string literal is interpreted by command line interpreter as an escape sequence. We can't avoid that.
