### ISSUE TITLE
Haxelib install error?

### ISSUE THREAD

**Issue by 448L** [HaxeFoundation/haxelib#513]
hi, i'm totally new to haxe, i've come for a game, i want to build it for myself, i'm using **Gnu/Debian 11 Bullseye** as operating system.
**(English is not my native language)**

when I use haxelib, after running `haxelib setup`, and then `haxelib install lime 7.9.0`, I get this error `Error:std@date_set_day`.
It also happens with the other libraries

**Comment by RealyUniqueName** [comment]
Is your system date/time correct?
Add `trace(year,month,day,hour,min,sec);` before this line https://github.com/HaxeFoundation/haxe/blob/e38302aef711de38a2fa2faf9f3b1eef02f3435a/std/neko/_std/Date.hx#L29
and see if the values make sense.

**Comment by Sen448** [comment]
> Is your system date/time correct?
Yes

**Comment by Sen448** [comment]
I tried
![imagen](https://user-images.githubusercontent.com/60526375/116825717-6bdf3d80-ab5e-11eb-9121-c4d67037f775.png)
I don't know if I did it wrong, but I still get the error.

**the date and time are correct** 

![imagen](https://user-images.githubusercontent.com/60526375/116825904-5f0f1980-ab5f-11eb-8af2-7b88c9bf33f9.png)

**Comment by Sen448** [comment]
I have tested again, this time on a virtual machine, with **Debian Bullseye** and **Fedora**.
I keep getting the same error.

Obviously here I have no idea why the error. 😅

**Comment by Sen448** [comment]
@RealyUniqueName Do you think it can be solved if I compile haxe? 😓

**Comment by 448L** [comment]
https://github.com/KadeDev/Kade-Engine/issues/648#issuecomment-887807736
