### ISSUE TITLE
No such version 4.0.2 for library haxelib

### ISSUE THREAD

**Issue by player-03** [HaxeFoundation/haxelib#533]
[Haxelib's latest haxelib.json file](https://github.com/HaxeFoundation/haxelib/blob/development/haxelib.json) says version 4.0.2, but [only version 3.3.0 was ever published](https://lib.haxe.org/p/haxelib/). As a result there's no easy way to update it:

```text
$ haxelib version
3.3.0
$ haxelib selfupdate
Warning: Command `selfupdate` is deprecated and will be removed in future. Use `haxelib --global update haxelib` instead.
$ haxelib update haxelib
haxelib is up to date
$ haxelib --global update haxelib
haxelib is up to date
$ haxelib install haxelib 4.0.2
Error: No such version 4.0.2 for library haxelib
```

Installing from git does work, but `update` really ought to be enough.

**Comment by tobil4sk** [comment]
Haxelib 4.0.3 has been pushed to haxelib now: https://lib.haxe.org/p/haxelib/4.0.3/, so `haxelib update` will no longer downgrade haxelib.
