### ISSUE TITLE
Regarding the Licence of the project

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxelib#534]
I would like to ask about the licence of the project (specifically the haxelib client code).

On one hand, most of the files in the project are marked with the MIT licence at the top of the file. However, the `./haxelib.json` file declares that the project is `GPL`. Is this a mistake or is there a reason behind the differing licences?

**Comment by Simn** [comment]
It should be MIT so that looks like some mistake.

**Comment by tobil4sk** [comment]
I created a PR to change what it says in `haxelib.json` (#535), assuming it's as simple as that.
