### ISSUE TITLE
[Enhancement?]: Add a .gitignore equivalent for haxelib

### ISSUE THREAD

**Issue by Cheemsandfriends** [HaxeFoundation/haxelib#551]
When you submit a lib in haxelib while using a folder, it seems that zips the whole thing without caring if there's some files that the owner doesn't want to put on the lib but on Github (like samples for something or unnecessary assets or folders.

My suggestion is to add an equivalent of gitignore, something like hxignore maybe?

**Comment by tobil4sk** [comment]
Just for reference, this is npm's solution to this: https://npm.github.io/publishing-pkgs-docs/publishing/the-npmignore-file.html

**Comment by tobil4sk** [comment]
Actually, I just realised this has been mentioned in #315, so we'll move this there.

**Comment by Cheemsandfriends** [comment]
> Actually, I just realised this has been mentioned in #315, so we'll move this there.

Damn, 2016?????
Why wouldn't they implement an hxlibignore rn if it was an oldass request?

**Comment by tobil4sk** [comment]
Well there wasn't much Haxelib development because the codebase wasn't very organised and no one wanted to touch it... but now there's been a PR to reorganise it a bit which should hopefully make adding features easier.
