### ISSUE TITLE
Legacy site is down

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxelib#558]
https://lib.haxe.org/legacy/

Error given:
```
Uncaught exception - /var/haxelib-s3fs/legacy/haxelib.db should be the same as /var/www/html/legacy/haxelib.db

Called from ? line 1
Called from legacyhaxelib/Site.hx line 261
Called from legacyhaxelib/Site.hx line 45
Called from legacyhaxelib/Site.hx line 47
```

**Comment by Digivorix** [comment]
This is becoming an issue for me as well. I need to access the HaXe 2 random library for one of my projects. For some reason it appears I've deleted my HaXe 2 installation, and now no longer have those library files. I hope someone can fix this soon.

**Comment by tobil4sk** [comment]
@andyli it looks like the legacy server was missed out in the changes here perhaps? https://github.com/HaxeFoundation/haxelib/commit/a5ced1047a33319dc96b0eca97518581910954d7

#575 has fixed the legacy server when setting up local testing instances. It looks like the site isn't crashing now on the development version of [the site](https://development-lib.haxe.org/legacy/), but it still doesn't seem to be able to connect to the actual database.

**Comment by tobil4sk** [comment]
@andyli The legacy site functionality was partially restored on the development build of the site in fc1f0608b95e92f73bdefb7c7b0e48b7dc382158, but since then there is now a new error message. Could any of your recent changes have anything to do with it?

```
Uncaught exception - /var/haxelib-s3fs/legacy/haxelib.db does not exist.

Called from ? line 1
Called from legacyhaxelib/Site.hx line 258
Called from legacyhaxelib/Site.hx line 41
Called from haxelib/server/FileStorage.hx line 149
```

**Comment by andyli** [comment]
Thanks for the head up. Will look at that later.

**Comment by andyli** [comment]
It's up now. Checked the haxelib.exe from haxe 2.10 also works.

**Comment by tobil4sk** [comment]
Works great now! Might still be worth considering why exactly this check was failing, since it had to be commented out: https://github.com/HaxeFoundation/haxelib/blob/e789fe1dd8203bcadaf457327e54cb332b4dca58/src/legacyhaxelib/Site.hx#L42-L43

Also, there is still a slight issue with the legacy site in local instances of the server. There is a "setup" command to initialise the database, however, it fails because `initDatabase()` runs before this setup actually occurs. Since `initDatabase` throws if the database has not been created, it makes the setup command useless.
https://github.com/HaxeFoundation/haxelib/blob/e789fe1dd8203bcadaf457327e54cb332b4dca58/src/legacyhaxelib/Site.hx#L257
https://github.com/HaxeFoundation/haxelib/blob/e789fe1dd8203bcadaf457327e54cb332b4dca58/src/legacyhaxelib/Site.hx#L60-L64

Maybe the setup code should be moved into main, so that the command line arguments are checked for `setup` before running `initDatabase()`? It's not as important since the main site works now, but it would be useful to have it working for local testing in case anything comes up again.

**Comment by Simn** [comment]
@tobil4sk Didn't we discuss (and fix) this before?

**Comment by tobil4sk** [comment]
The fix had to be reverted at the time because it didn't work with the live server: fc1f0608b95e92f73bdefb7c7b0e48b7dc382158.

However, with c2d3b9eeccf12fe46cd00a24f93e5f69d5adc5fc now it looks like the live server has been changed, so actually, something like this could work again: #588
