### ISSUE TITLE
Installing anything always fails

### ISSUE THREAD

**Issue by Zatistic** [HaxeFoundation/haxelib#578]
Hi
So I have downloaded haxe and I want to install lime, openfl, and flixel using `haxelib install lime` and `haxelib install openfl` and also `haxelib install flixel` So the installing works but it always fails, So whats wrong?

**Comment by kLabz** [comment]
How does it works and how does it fail?

**Comment by Zatistic** [comment]
To fail, It doesn't reach the max MB So like openfl is 2.7 MB and it never goes 2.7 MB its been 3/3 so it always fails

**Comment by Zatistic** [comment]
Oh wait its fixed
