### ISSUE TITLE
Library not being showed properly

### ISSUE THREAD

**Issue by Cheemsandfriends** [HaxeFoundation/haxelib#587]
Hi!
I've been having some issue for quite some time about a library i've been maintaining called FlxAnimate
when I search on the haxelib search bar, it doesn't show, like if it didn't exist at all!
![imagen](https://user-images.githubusercontent.com/84867412/219977086-956af5c8-1ad8-4915-8327-b77609e4e68d.png)
Also that, if you look on the library itself you may have two things happening:
1. The page doesn't exist, like if it actually didnt exist or it was banned for some reason

![imagen](https://user-images.githubusercontent.com/84867412/219977175-6c4af42b-0d17-4436-a56c-30a325eb8387.png)
3. The page appears, like it should as if nothing happened, but haxelib detects that the "latest" version of 
the lib is null (even tho you may be in the actual latest version, in this case 3.0.4)

![imagen](https://user-images.githubusercontent.com/84867412/219977232-b87b5b37-d97e-43a0-ad5c-91a9e5ae08df.png)

I dont really know what I would have done to cause this issue exactly, or why it is happening at all, but it is happening for some reason.

**Comment by andyli** [comment]
My bad. A few days ago I noticed somehow there were duplicated FlxAnimate 3.0.4 version records in the db, so I manually deleted the duplicated entries, but forgot to check the latest version field in the project table.

I've just fixed it. If there is any abnormalities, please report.
