### ISSUE TITLE
Haxelib setup fails on CentOS

### ISSUE THREAD

**Issue by ConfidantCommunications** [HaxeFoundation/haxelib#594]
I successfully installed Haxe using the [CentOS instructions](https://haxe.org/download/linux/). When I attempt to run the `haxelib setup` command it returns the error:
Segmentation fault (core dumped)

What should I do?

**Comment by andyli** [comment]
Right, I wouldn't work on the CentOS packages anymore. Should have removed it from https://haxe.org/download/linux/.
