### ISSUE TITLE
I want to remove my library, but i don't find the right command

### ISSUE THREAD

**Issue by ZigRazor** [HaxeFoundation/haxelib#595]
Hi, 
I entered the library incorrectly ( my library is in C++, I misunderstood the meaning of haxelib ), and I want to remove my library from the Haxelib.

Some details,
Author: ZigRazor
Library Name: CXXGraph

I would be grateful if someone could help me!

**Comment by andyli** [comment]
It's a manual process and this is the right place to ask.

I've just removed the project for you. Cheers.
