### ISSUE TITLE
Request to remove library from lib.haxe.org

### ISSUE THREAD

**Issue by TheWorldMachinima** [HaxeFoundation/haxelib#604]
I don't need this repository anymore, I'll push a better one soon.
Can you please delete it?

https://lib.haxe.org/p/SScript/

**Comment by andyli** [comment]
Usually we don't remove published libraries, unless

- there are leaked personal/private info, like password or keys, or
- there is code that is harmful to users, or
- it is absolutely unusable for technical reason, or
- it's very new that there is no evidence anyone used and depends on it.

Given SScript was first published 10 months already, and the download count is over hundred. I'm more inclined to keep it.

I would suggest you to publish a new version of SScript with a README saying that it's deprecated / orphaned / or any other helpful info.

**Comment by TheWorldMachinima** [comment]
> The problem is if we deleted/renamed an existing library, people who used and depends on the library can no longer get it via haxelib. We don't want to break people's code.

I know that, but I'll publish a new version that is completely compatible with the old library.
The only thing they'll need to do is rename the library in their projects.

**Comment by Aurel300** [comment]
Why not publish it under the same name, but a new version then?

**Comment by TheWorldMachinima** [comment]
> Why not publish it under the same name, but a new version then?

Because I hate this current name, I'd rather rename the library or delete it rather than releasing a new version.
