### ISSUE TITLE
Request to delete library

### ISSUE THREAD

**Issue by TheWorldMachinima** [HaxeFoundation/haxelib#606]
Library TeaScript has been replaced with SScript due to TeaScript being another scripting language, so I replaced TeaScript 1.0.1 with SScript 3.0.0.

Link to library:
https://lib.haxe.org/p/TeaScript/

**Comment by kLabz** [comment]
See #604

**Comment by TheWorldMachinima** [comment]
> See #604
SScript and TeaScript are completely the same, that means 2 same libraries with different names will exist in the server but alright.

**Comment by TheWorldMachinima** [comment]
> See #604

SScript and TeaScript are completely the same, that means 2 same libraries with different names will exist in the server but alright.
