### ISSUE TITLE
Request to delete faulty libraries

### ISSUE THREAD

**Issue by TahirRollingArch** [HaxeFoundation/haxelib#608]
Currently SScript and TeaScript both have all faulty versions and I want to re-release the library, so I want both of them deleted.

https://lib.haxe.org/p/SScript/
https://lib.haxe.org/p/TeaScript

**Comment by kLabz** [comment]
#604 #606

**Comment by TahirRollingArch** [comment]
> #604 #606

Can't you at least clear the versions?
