### ISSUE TITLE
Replaced with NekoVM on the Arch package

### ISSUE THREAD

**Issue by Xanderplayz16** [HaxeFoundation/haxelib#629]
For some reason, haxelib is just the NekoVM binary on the Arch package. They are exactly the same size. Haxe itself works fine though.

https://github.com/HaxeFoundation/haxelib/assets/74632800/4686c769-217b-434c-8d16-9c9954405965

**Comment by tobil4sk** [comment]
This is being handled in:
https://github.com/HaxeFoundation/haxe/issues/11652
 https://gitlab.archlinux.org/archlinux/packaging/packages/haxe/-/issues/2
