### ISSUE TITLE
Change password and username request

### ISSUE THREAD

**Issue by posxposy** [HaxeFoundation/haxelib#633]
Sorry, I didn't use haxelib for a long time and just registered a new account with the username `posxposy`, but I forgot that I already have one with the `dmitryhryppa` username.
So, may I ask you to remove the `posxposy` account, rename `dmitryhryppa` to `posxposy`, and then reset a password for it, please?
Thanks.

**Comment by andyli** [comment]
I sent you an email (to the address associated with the haxelib account).

**Comment by andyli** [comment]
Done
