### ISSUE TITLE
question

### ISSUE THREAD

**Issue by StinkTheStinker** [HaxeFoundation/haxelib#656]
![image](https://github.com/user-attachments/assets/d412bac8-6ea3-4b6c-a731-e014c0406870)

does anyone know what is going on here

file has not been edited

**Comment by moxie-coder** [comment]
you need Haxe 4.3, also this isn't the repo to make this issue

**Comment by StinkTheStinker** [comment]
> you need Haxe 4.3, also this isn't the repo to make this issue

...haxe/lib...

**Comment by moxie-coder** [comment]
> > you need Haxe 4.3, also this isn't the repo to make this issue
> 
> ...haxe/lib...

this isn't an haxelib issue, this is just an haxe issue, or rather an *you* issue
