### ISSUE TITLE
Clean up "dev" code

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxelib#68]
For example, <https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Main.hx#L1015>: 

	if( !FileSystem.exists(proj) ) {
		FileSystem.createDirectory(proj);
		File.saveContent(proj + "/.current", "dev");
	}

@dpeek pointed out that saving ".current" should probably happen outside of the if statement.  On further reading of the source though, that isn't necessary at all - we shouldn't write it to begin with.  Or if we do, we should reset it when disabling dev.

Either way it would be nice to make this more obvious, or possibly write some unit tests for it.

**Comment by back2dos** [comment]
What's with the original issue. Does this still need addressing?

**Comment by jasononeil** [comment]
Basically in some places (but not all) we set ".current" to the string "dev" when dev mode was enabled.  But this wasn't actually required - the existence of a ".dev" file is all that matters.  

Furthermore, it meant when you disabled dev mode on a library, it did not always restore the previous version as "current".

Fixed now.
