### ISSUE TITLE
haxelib bundle, or improved haxelib submit

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxelib#70]
We spoke about this at WWX, but it would be good to get some discussion / documentation going for this feature.

The idea:

    haxelib bundle - create a zip of the current directory

OR 

    haxelib submit (no-parameter), zip the current directory, and submit it.

MassiveLib has a function similar to this, and many people have shell scripts or bat files that do this, but it would be nice if haxelib took care of it.  

Questions to answer:

1. What is the proposed command / syntax / interaction?
2. Do we want to include an option to bump/change the version number?
3. Do we want an ability to specify which files to include in the zip, or alternatively, which files to ignore?  Would this be specified in haxelib.json, or in something else?

**Comment by back2dos** [comment]
Ok, I will change `submit` to either work with directories or `zip`. So to submit the current directory, it will be `haxelib submit .`.

**Comment by jasononeil** [comment]
:+1: :+1: :+1:

**Comment by jgranick** [comment]
Does this provide any filter? For example, I expect filtering `.DS_Store` or `.git` would be common

**Comment by back2dos** [comment]
For the time being anything with a leading dot is skipped: https://github.com/HaxeFoundation/haxelib/commit/94e233284e1bae7a1324e6ce58b7084465c4f2a3#diff-fd809aff323d8e96db532340a488fed5R386
