### ISSUE TITLE
When Haxelib selfupdate fails (no sudo), it will definitively no more work (OSX).

### ISSUE THREAD

**Issue by sledorze** [HaxeFoundation/haxelib#72]
Under OSX, when trying to selfupdate haxelib without sudo, it fails.
Then subsequent try to selfupdate it (with sudo) has no effect (considered as up to date).

Then if I try to install git projects, their dependencies resolution do not work.
Reproduced several time when trying to install scuts:
https://github.com/frabbit/scuts

with commands:
haxelib git scuts-core https://github.com/frabbit/scuts.git master scutsCore
haxelib git scuts-mcore https://github.com/frabbit/scuts.git master scutsMCore
haxelib git scuts-ds https://github.com/frabbit/scuts.git master scutsDs
haxelib git scuts-reactive https://github.com/frabbit/scuts.git master scutsReactive
haxelib git scuts-macros https://github.com/frabbit/scuts.git master scutsMacros
haxelib git scuts-ht https://github.com/frabbit/scuts.git master scutsHt

**Comment by back2dos** [comment]
What's the state of this?

**Comment by nadako** [comment]
This is now "fixed" as selfupdate doesn't try to change global haxelib executable file (#172)
