### ISSUE TITLE
Installed versions are not always displayed in "correct order" with haxelib list

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxelib#83]
This is a very minor issue, if it can be considered an issue at all. The versions installed don't always show in the "correct order" (oldest first, newest last). Like you can see on this screenshot, it seems to work perfectly for every lib but nape, where 2.0.9 shows up on the very right instead of on the left:

![](http://i.imgur.com/VlrqP8b.png)

**Comment by nadako** [comment]
I went ahead and added version sorting using current `SemVer.compare`
